# Example for: selection.assess_dope()

from modeller import *
from modeller.scripts import complete_pdb

env = environ()
env.libs.topology.read(file='$(LIB)/top_heav.lib')
env.libs.parameters.read(file='$(LIB)/par.lib')

# Read a model previously generated by Modeller's automodel class
mdl = complete_pdb(env, 'FAK1_2j0kB_yl_2.B99990001.pdb')

# Select all atoms in the first chain
atmsel = selection(mdl.chains[0])

score = atmsel.assess_dope()

