# pml automagically-generated by psntools 1.0

# molecule file name, you can change it with an other file of the same molecule
mol_file_name = "hFAK1_2j0j_al_yl2_1.pdb"

# cartoon color definition, change it as you please
set_color cartoon_color, [ 0.60, 0.60, 0.60 ]

# color definitions, change them as you please
set_color color_value_from_0_to_10,   [ 0.00, 0.00, 0.00 ]
set_color color_value_from_10_to_20,  [ 0.10, 0.10, 0.10 ]
set_color color_value_from_20_to_30,  [ 0.30, 0.30, 0.30 ]
set_color color_value_from_30_to_40,  [ 0.60, 0.60, 0.60 ]
set_color color_value_from_40_to_50,  [ 0.00, 0.00, 1.00 ]
set_color color_value_from_50_to_60,  [ 0.00, 0.50, 1.00 ]
set_color color_value_from_60_to_70,  [ 0.00, 1.00, 0.00 ]
set_color color_value_from_70_to_80,  [ 1.00, 1.00, 0.00 ]
set_color color_value_from_80_to_90,  [ 1.00, 0.60, 0.00 ]
set_color color_value_from_90_to_100, [ 1.00, 0.00, 0.00 ]

# color definitions, change them as you please
set_color color_num_0,   [ 0.00, 0.00, 0.00 ]
set_color color_num_1,   [ 1.00, 0.00, 0.00 ]
set_color color_num_2,   [ 0.00, 1.00, 0.00 ]
set_color color_num_3,   [ 0.00, 0.00, 1.00 ]
set_color color_num_4,   [ 1.00, 1.00, 0.00 ]
set_color color_num_5,   [ 0.00, 1.00, 1.00 ]
set_color color_num_6,   [ 1.00, 0.00, 1.00 ]
set_color color_num_7,   [ 0.80, 1.00, 0.00 ]
set_color color_num_8,   [ 1.00, 0.70, 0.70 ]
set_color color_num_9,   [ 1.00, 0.70, 0.20 ]
set_color color_num_10,  [ 0.00, 0.60, 1.00 ]
set_color color_num_11,  [ 0.54, 0.31, 0.64 ]
set_color color_num_12,  [ 1.00, 0.50, 1.00 ]
set_color color_num_13,  [ 0.20, 0.60, 0.20 ]
set_color color_num_14,  [ 1.00, 0.12, 0.00 ]
set_color color_num_15,  [ 1.00, 0.24, 0.00 ]
set_color color_num_16,  [ 1.00, 0.36, 0.00 ]
set_color color_num_17,  [ 1.00, 0.48, 0.00 ]
set_color color_num_18,  [ 1.00, 0.60, 0.00 ]
set_color color_num_19,  [ 1.00, 0.72, 0.00 ]
set_color color_num_20,  [ 1.00, 0.84, 0.00 ]
set_color color_num_21,  [ 1.00, 0.96, 0.00 ]
set_color color_num_22,  [ 0.92, 1.00, 0.00 ]
set_color color_num_23,  [ 0.80, 1.00, 0.00 ]
set_color color_num_24,  [ 0.68, 1.00, 0.00 ]
set_color color_num_25,  [ 0.56, 1.00, 0.00 ]
set_color color_num_26,  [ 0.44, 1.00, 0.00 ]
set_color color_num_27,  [ 0.32, 1.00, 0.00 ]
set_color color_num_28,  [ 0.20, 1.00, 0.00 ]
set_color color_num_29,  [ 0.08, 1.00, 0.00 ]
set_color color_num_30,  [ 0.00, 1.00, 0.04 ]
set_color color_num_31,  [ 0.00, 1.00, 0.16 ]
set_color color_num_32,  [ 0.00, 1.00, 0.28 ]
set_color color_num_33,  [ 0.00, 1.00, 0.40 ]
set_color color_num_34,  [ 0.00, 1.00, 0.52 ]
set_color color_num_35,  [ 0.00, 1.00, 0.64 ]
set_color color_num_36,  [ 0.00, 1.00, 0.76 ]
set_color color_num_37,  [ 0.00, 1.00, 0.88 ]
set_color color_num_38,  [ 0.00, 1.00, 1.00 ]
set_color color_num_39,  [ 0.00, 0.88, 1.00 ]
set_color color_num_40,  [ 0.00, 0.76, 1.00 ]
set_color color_num_41,  [ 0.00, 0.64, 1.00 ]
set_color color_num_42,  [ 0.00, 0.52, 1.00 ]
set_color color_num_43,  [ 0.00, 0.40, 1.00 ]
set_color color_num_44,  [ 0.00, 0.28, 1.00 ]
set_color color_num_45,  [ 0.00, 0.16, 1.00 ]
set_color color_num_46,  [ 0.00, 0.04, 1.00 ]
set_color color_num_47,  [ 0.08, 0.00, 1.00 ]
set_color color_num_48,  [ 0.20, 0.00, 1.00 ]
set_color color_num_49,  [ 0.32, 0.00, 1.00 ]
set_color color_num_50,  [ 0.44, 0.00, 1.00 ]
set_color color_num_51,  [ 0.56, 0.00, 1.00 ]
set_color color_num_52,  [ 0.68, 0.00, 1.00 ]
set_color color_num_53,  [ 0.80, 0.00, 1.00 ]
set_color color_num_54,  [ 0.92, 0.00, 1.00 ]
set_color color_num_55,  [ 1.00, 0.00, 0.96 ]
set_color color_num_56,  [ 1.00, 0.00, 0.84 ]
set_color color_num_57,  [ 1.00, 0.00, 0.72 ]
set_color color_num_58,  [ 1.00, 0.00, 0.60 ]
set_color color_num_59,  [ 1.00, 0.00, 0.48 ]
set_color color_num_60,  [ 1.00, 0.00, 0.36 ]
set_color color_num_61,  [ 1.00, 0.00, 0.24 ]
set_color color_num_62,  [ 1.00, 0.00, 0.12 ]

# fixed size radius used for clusters and communities, change them as you please
link_fixed_size_value = 4.0
node_fixed_size_value = 1.0
hub_fixed_size_value  = 1.8

# link size definitions, change them as you please
link_size_value_from_0_to_10   = 2.5
link_size_value_from_10_to_20  = 3.0
link_size_value_from_20_to_30  = 3.5
link_size_value_from_30_to_40  = 4.0
link_size_value_from_40_to_50  = 4.5
link_size_value_from_50_to_60  = 5.0
link_size_value_from_60_to_70  = 5.5
link_size_value_from_70_to_80  = 6.0
link_size_value_from_80_to_90  = 6.5
link_size_value_from_90_to_100 = 7.0

# node size definitions, change them as you please
node_size_value_from_0_to_10   = 0.5
node_size_value_from_10_to_20  = 0.6
node_size_value_from_20_to_30  = 0.7
node_size_value_from_30_to_40  = 0.8
node_size_value_from_40_to_50  = 0.9
node_size_value_from_50_to_60  = 1.0
node_size_value_from_60_to_70  = 1.1
node_size_value_from_70_to_80  = 1.2
node_size_value_from_80_to_90  = 1.3
node_size_value_from_90_to_100 = 1.4

# diff colors definitions, change them as you please
set_color net1_items_color,   [ 1.0, 0.5, 0.0 ]
set_color shared_items_color, [ 0.5, 1.0, 0.0 ]
set_color net2_items_color,   [ 0.8, 0.5, 1.0 ]

# pert colors definitions, change them as you please
set_color color_pert_neg_75_100, [ 0.00, 0.00, 1.00 ]
set_color color_pert_neg_50_75,  [ 0.00, 0.37, 1.00 ]
set_color color_pert_neg_25_50,  [ 0.00, 0.75, 1.00 ]
set_color color_pert_neg_0_25,   [ 0.00, 1.00, 1.00 ]
set_color color_pert_zero,       [ 1.00, 1.00, 1.00 ]
set_color color_pert_pos_75_100, [ 1.00, 0.00, 0.00 ]
set_color color_pert_pos_50_75,  [ 1.00, 0.37, 0.00 ]
set_color color_pert_pos_25_50,  [ 1.00, 0.75, 0.00 ]
set_color color_pert_pos_0_25,   [ 1.00, 1.00, 0.00 ]

# some other graphic settings, change them as you please
cartoon automatic
set cartoon_smooth_loops=0
set cartoon_fancy_helices=1
set transparency_mode=1
set ray_shadows=0
set ray_transparency_shadows=0
set cartoon_transparency=0.6
bg_color white
set ortho=on
set depth_cue=off
set ray_trace_fog=0
set antialias=1
set dash_gap,0.0
set dash_round_ends,on
set dash_width,3.0
set dash_radius,0.0
print("this is PSN_comms.pml")



# =========================================== #
# PLEASE DO NOT EDIT ANYTHING BELOW THIS LINE #
# =========================================== #



cmd.load(mol_file_name, "molcart")
dss molcart
hide everything, molcart
color cartoon_color, molcart
show cartoon, molcart

sele notpol, molcart and not polymer
show sticks, notpol
cmd.load(mol_file_name, "psg")
hide everything, psg
# link: A:A:F40 A:A:K38
cmd.dist("link1", "psg and A/A/40/CA", "psg and A/A/38/CA", label = 0, width = link_fixed_size_value)
color color_num_9, link1
# link: A:A:A53 A:A:K38
cmd.dist("link2", "psg and A/A/53/CA", "psg and A/A/38/CA", label = 0, width = link_fixed_size_value)
color color_num_9, link2
# link: A:A:A53 A:A:F40
cmd.dist("link3", "psg and A/A/53/CA", "psg and A/A/40/CA", label = 0, width = link_fixed_size_value)
color color_num_9, link3
# link: A:A:E123 A:A:Y42
cmd.dist("link4", "psg and A/A/123/CA", "psg and A/A/42/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link4
# link: A:A:R125 A:A:Y42
cmd.dist("link5", "psg and A/A/125/CA", "psg and A/A/42/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link5
# link: A:A:F146 A:A:Y42
cmd.dist("link6", "psg and A/A/146/CA", "psg and A/A/42/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link6
# link: A:A:Q150 A:A:Y42
cmd.dist("link7", "psg and A/A/150/CA", "psg and A/A/42/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link7
# link: A:A:F43 A:A:Y83
cmd.dist("link8", "psg and A/A/43/CA", "psg and A/A/83/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link8
# link: A:A:F146 A:A:F43
cmd.dist("link9", "psg and A/A/146/CA", "psg and A/A/43/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link9
# link: A:A:E44 A:A:W52
cmd.dist("link10", "psg and A/A/44/CA", "psg and A/A/52/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link10
# link: A:A:E44 A:A:Q149
cmd.dist("link11", "psg and A/A/44/CA", "psg and A/A/149/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link11
# link: A:A:E44 A:A:R178
cmd.dist("link12", "psg and A/A/44/CA", "psg and A/A/178/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link12
# link: A:A:S45 A:A:S47
cmd.dist("link13", "psg and A/A/45/CA", "psg and A/A/47/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link13
# link: A:A:S45 A:A:W52
cmd.dist("link14", "psg and A/A/45/CA", "psg and A/A/52/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link14
# link: A:A:S47 A:A:W52
cmd.dist("link15", "psg and A/A/47/CA", "psg and A/A/52/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link15
# link: A:A:Q149 A:A:W52
cmd.dist("link16", "psg and A/A/149/CA", "psg and A/A/52/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link16
# link: A:A:V72 A:A:V77
cmd.dist("link17", "psg and A/A/72/CA", "psg and A/A/77/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link17
# link: A:A:V72 A:A:Y83
cmd.dist("link18", "psg and A/A/72/CA", "psg and A/A/83/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link18
# link: A:A:V77 A:A:Y83
cmd.dist("link19", "psg and A/A/77/CA", "psg and A/A/83/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link19
# link: A:A:T143 A:A:V77
cmd.dist("link20", "psg and A/A/143/CA", "psg and A/A/77/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link20
# link: A:A:C82 A:A:P130
cmd.dist("link21", "psg and A/A/82/CA", "psg and A/A/130/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link21
# link: A:A:C82 A:A:F137
cmd.dist("link22", "psg and A/A/82/CA", "psg and A/A/137/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link22
# link: A:A:L124 A:A:Y83
cmd.dist("link23", "psg and A/A/124/CA", "psg and A/A/83/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link23
# link: A:A:I126 A:A:Y83
cmd.dist("link24", "psg and A/A/126/CA", "psg and A/A/83/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link24
# link: A:A:T143 A:A:Y83
cmd.dist("link25", "psg and A/A/143/CA", "psg and A/A/83/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link25
# link: A:A:F146 A:A:Y83
cmd.dist("link26", "psg and A/A/146/CA", "psg and A/A/83/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link26
# link: A:A:R86 A:A:W97
cmd.dist("link27", "psg and A/A/86/CA", "psg and A/A/97/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link27
# link: A:A:E123 A:A:R86
cmd.dist("link28", "psg and A/A/123/CA", "psg and A/A/86/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link28
# link: A:A:R125 A:A:R86
cmd.dist("link29", "psg and A/A/125/CA", "psg and A/A/86/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link29
# link: A:A:L87 A:A:Y111
cmd.dist("link30", "psg and A/A/87/CA", "psg and A/A/111/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link30
# link: A:A:L87 A:A:W120
cmd.dist("link31", "psg and A/A/87/CA", "psg and A/A/120/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link31
# link: A:A:H115 A:A:H89
cmd.dist("link32", "psg and A/A/115/CA", "psg and A/A/89/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link32
# link: A:A:E119 A:A:H89
cmd.dist("link33", "psg and A/A/119/CA", "psg and A/A/89/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link33
# link: A:A:H89 A:A:W120
cmd.dist("link34", "psg and A/A/89/CA", "psg and A/A/120/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link34
# link: A:A:R125 A:A:W97
cmd.dist("link35", "psg and A/A/125/CA", "psg and A/A/97/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link35
# link: A:A:R127 A:A:W97
cmd.dist("link36", "psg and A/A/127/CA", "psg and A/A/97/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link36
# link: A:A:D342 A:A:W97
cmd.dist("link37", "psg and A/A/342/CA", "psg and A/A/97/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link37
# link: A:A:D345 A:A:H99
cmd.dist("link38", "psg and A/A/345/CA", "psg and A/A/99/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link38
# link: A:A:H99 A:A:S357
cmd.dist("link39", "psg and A/A/99/CA", "psg and A/A/357/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link39
# link: A:A:W120 A:A:Y111
cmd.dist("link40", "psg and A/A/120/CA", "psg and A/A/111/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link40
# link: A:A:E119 A:A:H115
cmd.dist("link41", "psg and A/A/119/CA", "psg and A/A/115/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link41
# link: A:A:H115 A:A:W120
cmd.dist("link42", "psg and A/A/115/CA", "psg and A/A/120/CA", label = 0, width = link_fixed_size_value)
color color_num_5, link42
# link: A:A:E123 A:A:R125
cmd.dist("link43", "psg and A/A/123/CA", "psg and A/A/125/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link43
# link: A:A:F146 A:A:L124
cmd.dist("link44", "psg and A/A/146/CA", "psg and A/A/124/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link44
# link: A:A:Q150 A:A:R125
cmd.dist("link45", "psg and A/A/150/CA", "psg and A/A/125/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link45
# link: A:A:F146 A:A:I126
cmd.dist("link46", "psg and A/A/146/CA", "psg and A/A/126/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link46
# link: A:A:F147 A:A:I126
cmd.dist("link47", "psg and A/A/147/CA", "psg and A/A/126/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link47
# link: A:A:I126 A:A:Q150
cmd.dist("link48", "psg and A/A/126/CA", "psg and A/A/150/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link48
# link: A:A:R127 A:A:Y128
cmd.dist("link49", "psg and A/A/127/CA", "psg and A/A/128/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link49
# link: A:A:E256 A:A:R127
cmd.dist("link50", "psg and A/A/256/CA", "psg and A/A/127/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link50
# link: A:A:D342 A:A:R127
cmd.dist("link51", "psg and A/A/342/CA", "psg and A/A/127/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link51
# link: A:A:L343 A:A:R127
cmd.dist("link52", "psg and A/A/343/CA", "psg and A/A/127/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link52
# link: A:A:D342 A:A:Y128
cmd.dist("link53", "psg and A/A/342/CA", "psg and A/A/128/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link53
# link: A:A:F137 A:A:P130
cmd.dist("link54", "psg and A/A/137/CA", "psg and A/A/130/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link54
# link: A:A:F137 A:A:T143
cmd.dist("link55", "psg and A/A/137/CA", "psg and A/A/143/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link55
# link: A:A:F137 A:A:F147
cmd.dist("link56", "psg and A/A/137/CA", "psg and A/A/147/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link56
# link: A:A:F147 A:A:V151
cmd.dist("link57", "psg and A/A/147/CA", "psg and A/A/151/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link57
# link: A:A:F147 A:A:F244
cmd.dist("link58", "psg and A/A/147/CA", "psg and A/A/244/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link58
# link: A:A:Q149 A:A:Y148
cmd.dist("link59", "psg and A/A/149/CA", "psg and A/A/148/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link59
# link: A:A:K152 A:A:Y148
cmd.dist("link60", "psg and A/A/152/CA", "psg and A/A/148/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link60
# link: A:A:E175 A:A:Y148
cmd.dist("link61", "psg and A/A/175/CA", "psg and A/A/148/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link61
# link: A:A:R178 A:A:Y148
cmd.dist("link62", "psg and A/A/178/CA", "psg and A/A/148/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link62
# link: A:A:I240 A:A:Y148
cmd.dist("link63", "psg and A/A/240/CA", "psg and A/A/148/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link63
# link: A:A:K152 A:A:Q149
cmd.dist("link64", "psg and A/A/152/CA", "psg and A/A/149/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link64
# link: A:A:Q149 A:A:R178
cmd.dist("link65", "psg and A/A/149/CA", "psg and A/A/178/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link65
# link: A:A:F244 A:A:V151
cmd.dist("link66", "psg and A/A/244/CA", "psg and A/A/151/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link66
# link: A:A:F253 A:A:V151
cmd.dist("link67", "psg and A/A/253/CA", "psg and A/A/151/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link67
# link: A:A:E175 A:A:K152
cmd.dist("link68", "psg and A/A/175/CA", "psg and A/A/152/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link68
# link: A:A:K170 A:A:Q230
cmd.dist("link69", "psg and A/A/170/CA", "psg and A/A/230/CA", label = 0, width = link_fixed_size_value)
color color_num_11, link69
# link: A:A:F231 A:A:K170
cmd.dist("link70", "psg and A/A/231/CA", "psg and A/A/170/CA", label = 0, width = link_fixed_size_value)
color color_num_11, link70
# link: A:A:E175 A:A:R178
cmd.dist("link71", "psg and A/A/175/CA", "psg and A/A/178/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link71
# link: A:A:E175 A:A:S179
cmd.dist("link72", "psg and A/A/175/CA", "psg and A/A/179/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link72
# link: A:A:I240 A:A:R178
cmd.dist("link73", "psg and A/A/240/CA", "psg and A/A/178/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link73
# link: A:A:S179 A:A:Y180
cmd.dist("link74", "psg and A/A/179/CA", "psg and A/A/180/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link74
# link: A:A:R597 A:A:S179
cmd.dist("link75", "psg and A/A/597/CA", "psg and A/A/179/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link75
# link: A:A:F596 A:A:Y180
cmd.dist("link76", "psg and A/A/596/CA", "psg and A/A/180/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link76
# link: A:A:R597 A:A:Y180
cmd.dist("link77", "psg and A/A/597/CA", "psg and A/A/180/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link77
# link: A:A:L188 A:A:M183
cmd.dist("link78", "psg and A/A/188/CA", "psg and A/A/183/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link78
# link: A:A:F228 A:A:M183
cmd.dist("link79", "psg and A/A/228/CA", "psg and A/A/183/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link79
# link: A:A:M183 A:A:N595
cmd.dist("link80", "psg and A/A/183/CA", "psg and A/A/595/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link80
# link: A:A:F228 A:A:L188
cmd.dist("link81", "psg and A/A/228/CA", "psg and A/A/188/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link81
# link: A:A:K190 A:A:N193
cmd.dist("link82", "psg and A/A/190/CA", "psg and A/A/193/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link82
# link: A:A:E636 A:A:K190
cmd.dist("link83", "psg and A/A/636/CA", "psg and A/A/190/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link83
# link: A:A:K190 A:A:Y661
cmd.dist("link84", "psg and A/A/190/CA", "psg and A/A/661/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link84
# link: A:A:N193 A:A:N595
cmd.dist("link85", "psg and A/A/193/CA", "psg and A/A/595/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link85
# link: A:A:F596 A:A:N193
cmd.dist("link86", "psg and A/A/596/CA", "psg and A/A/193/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link86
# link: A:A:N193 A:A:Y661
cmd.dist("link87", "psg and A/A/193/CA", "psg and A/A/661/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link87
# link: A:A:F207 A:A:P208
cmd.dist("link88", "psg and A/A/207/CA", "psg and A/A/208/CA", label = 0, width = link_fixed_size_value)
color color_num_10, link88
# link: A:A:F207 A:A:L211
cmd.dist("link89", "psg and A/A/207/CA", "psg and A/A/211/CA", label = 0, width = link_fixed_size_value)
color color_num_10, link89
# link: A:A:L211 A:A:P208
cmd.dist("link90", "psg and A/A/211/CA", "psg and A/A/208/CA", label = 0, width = link_fixed_size_value)
color color_num_10, link90
# link: A:A:F231 A:A:Q230
cmd.dist("link91", "psg and A/A/231/CA", "psg and A/A/230/CA", label = 0, width = link_fixed_size_value)
color color_num_11, link91
# link: A:A:F244 A:A:F253
cmd.dist("link92", "psg and A/A/244/CA", "psg and A/A/253/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link92
# link: A:A:E256 A:A:L343
cmd.dist("link93", "psg and A/A/256/CA", "psg and A/A/343/CA", label = 0, width = link_fixed_size_value)
color color_num_1, link93
# link: A:A:C288 A:A:D285
cmd.dist("link94", "psg and A/A/288/CA", "psg and A/A/285/CA", label = 0, width = link_fixed_size_value)
color color_num_12, link94
# link: A:A:D285 A:A:N289
cmd.dist("link95", "psg and A/A/285/CA", "psg and A/A/289/CA", label = 0, width = link_fixed_size_value)
color color_num_12, link95
# link: A:A:C288 A:A:N289
cmd.dist("link96", "psg and A/A/288/CA", "psg and A/A/289/CA", label = 0, width = link_fixed_size_value)
color color_num_12, link96
# link: A:A:D345 A:A:I302
cmd.dist("link97", "psg and A/A/345/CA", "psg and A/A/302/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link97
# link: A:A:I302 A:A:I359
cmd.dist("link98", "psg and A/A/302/CA", "psg and A/A/359/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link98
# link: A:A:D345 A:A:S357
cmd.dist("link99", "psg and A/A/345/CA", "psg and A/A/357/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link99
# link: A:A:D345 A:A:I359
cmd.dist("link100", "psg and A/A/345/CA", "psg and A/A/359/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link100
# link: A:A:I359 A:A:S357
cmd.dist("link101", "psg and A/A/359/CA", "psg and A/A/357/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link101
# link: A:A:E416 A:A:T412
cmd.dist("link102", "psg and A/A/416/CA", "psg and A/A/412/CA", label = 0, width = link_fixed_size_value)
color color_num_13, link102
# link: A:A:T412 A:A:T491
cmd.dist("link103", "psg and A/A/412/CA", "psg and A/A/491/CA", label = 0, width = link_fixed_size_value)
color color_num_13, link103
# link: A:A:E416 A:A:T491
cmd.dist("link104", "psg and A/A/416/CA", "psg and A/A/491/CA", label = 0, width = link_fixed_size_value)
color color_num_13, link104
# link: A:A:I490 A:A:R419
cmd.dist("link105", "psg and A/A/490/CA", "psg and A/A/419/CA", label = 0, width = link_fixed_size_value)
color color_num_8, link105
# link: A:A:R419 A:A:W496
cmd.dist("link106", "psg and A/A/419/CA", "psg and A/A/496/CA", label = 0, width = link_fixed_size_value)
color color_num_8, link106
# link: A:A:I453 A:A:L424
cmd.dist("link107", "psg and A/A/453/CA", "psg and A/A/424/CA", label = 0, width = link_fixed_size_value)
color color_num_8, link107
# link: A:A:L424 A:A:W496
cmd.dist("link108", "psg and A/A/424/CA", "psg and A/A/496/CA", label = 0, width = link_fixed_size_value)
color color_num_8, link108
# link: A:A:E572 A:A:Q432
cmd.dist("link109", "psg and A/A/572/CA", "psg and A/A/432/CA", label = 0, width = link_fixed_size_value)
color color_num_14, link109
# link: A:A:E445 A:A:S443
cmd.dist("link110", "psg and A/A/445/CA", "psg and A/A/443/CA", label = 0, width = link_fixed_size_value)
color color_num_15, link110
# link: A:A:N446 A:A:S443
cmd.dist("link111", "psg and A/A/446/CA", "psg and A/A/443/CA", label = 0, width = link_fixed_size_value)
color color_num_15, link111
# link: A:A:E445 A:A:N446
cmd.dist("link112", "psg and A/A/445/CA", "psg and A/A/446/CA", label = 0, width = link_fixed_size_value)
color color_num_15, link112
# link: A:A:I453 A:A:W496
cmd.dist("link113", "psg and A/A/453/CA", "psg and A/A/496/CA", label = 0, width = link_fixed_size_value)
color color_num_8, link113
# link: A:A:F478 A:A:L537
cmd.dist("link114", "psg and A/A/478/CA", "psg and A/A/537/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link114
# link: A:A:F478 A:A:F542
cmd.dist("link115", "psg and A/A/478/CA", "psg and A/A/542/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link115
# link: A:A:F478 A:A:F565
cmd.dist("link116", "psg and A/A/478/CA", "psg and A/A/565/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link116
# link: A:A:H480 A:A:P481
cmd.dist("link117", "psg and A/A/480/CA", "psg and A/A/481/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link117
# link: A:A:H480 A:A:H482
cmd.dist("link118", "psg and A/A/480/CA", "psg and A/A/482/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link118
# link: A:A:H480 A:A:I483
cmd.dist("link119", "psg and A/A/480/CA", "psg and A/A/483/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link119
# link: A:A:H480 A:A:T532
cmd.dist("link120", "psg and A/A/480/CA", "psg and A/A/532/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link120
# link: A:A:H482 A:A:P481
cmd.dist("link121", "psg and A/A/482/CA", "psg and A/A/481/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link121
# link: A:A:H482 A:A:T532
cmd.dist("link122", "psg and A/A/482/CA", "psg and A/A/532/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link122
# link: A:A:I483 A:A:L537
cmd.dist("link123", "psg and A/A/483/CA", "psg and A/A/537/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link123
# link: A:A:F565 A:A:I483
cmd.dist("link124", "psg and A/A/565/CA", "psg and A/A/483/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link124
# link: A:A:I490 A:A:W496
cmd.dist("link125", "psg and A/A/490/CA", "psg and A/A/496/CA", label = 0, width = link_fixed_size_value)
color color_num_8, link125
# link: A:A:F510 A:A:R514
cmd.dist("link126", "psg and A/A/510/CA", "psg and A/A/514/CA", label = 0, width = link_fixed_size_value)
color color_num_16, link126
# link: A:A:F510 A:A:L518
cmd.dist("link127", "psg and A/A/510/CA", "psg and A/A/518/CA", label = 0, width = link_fixed_size_value)
color color_num_16, link127
# link: A:A:L518 A:A:R514
cmd.dist("link128", "psg and A/A/518/CA", "psg and A/A/514/CA", label = 0, width = link_fixed_size_value)
color color_num_16, link128
# link: A:A:I547 A:A:L534
cmd.dist("link129", "psg and A/A/547/CA", "psg and A/A/534/CA", label = 0, width = link_fixed_size_value)
color color_num_7, link129
# link: A:A:F608 A:A:L534
cmd.dist("link130", "psg and A/A/608/CA", "psg and A/A/534/CA", label = 0, width = link_fixed_size_value)
color color_num_7, link130
# link: A:A:F669 A:A:L534
cmd.dist("link131", "psg and A/A/669/CA", "psg and A/A/534/CA", label = 0, width = link_fixed_size_value)
color color_num_7, link131
# link: A:A:F542 A:A:L537
cmd.dist("link132", "psg and A/A/542/CA", "psg and A/A/537/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link132
# link: A:A:F565 A:A:L537
cmd.dist("link133", "psg and A/A/565/CA", "psg and A/A/537/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link133
# link: A:A:F542 A:A:F565
cmd.dist("link134", "psg and A/A/542/CA", "psg and A/A/565/CA", label = 0, width = link_fixed_size_value)
color color_num_4, link134
# link: A:A:H544 A:A:I547
cmd.dist("link135", "psg and A/A/544/CA", "psg and A/A/547/CA", label = 0, width = link_fixed_size_value)
color color_num_7, link135
# link: A:A:D604 A:A:H544
cmd.dist("link136", "psg and A/A/604/CA", "psg and A/A/544/CA", label = 0, width = link_fixed_size_value)
color color_num_7, link136
# link: A:A:D546 A:A:R550
cmd.dist("link137", "psg and A/A/546/CA", "psg and A/A/550/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link137
# link: A:A:D546 A:A:N551
cmd.dist("link138", "psg and A/A/546/CA", "psg and A/A/551/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link138
# link: A:A:D604 A:A:I547
cmd.dist("link139", "psg and A/A/604/CA", "psg and A/A/547/CA", label = 0, width = link_fixed_size_value)
color color_num_7, link139
# link: A:A:A548 A:A:R550
cmd.dist("link140", "psg and A/A/548/CA", "psg and A/A/550/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link140
# link: A:A:A548 A:A:W588
cmd.dist("link141", "psg and A/A/548/CA", "psg and A/A/588/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link141
# link: A:A:N551 A:A:R550
cmd.dist("link142", "psg and A/A/551/CA", "psg and A/A/550/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link142
# link: A:A:P585 A:A:R550
cmd.dist("link143", "psg and A/A/585/CA", "psg and A/A/550/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link143
# link: A:A:R550 A:A:W588
cmd.dist("link144", "psg and A/A/550/CA", "psg and A/A/588/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link144
# link: A:A:P585 A:A:W588
cmd.dist("link145", "psg and A/A/585/CA", "psg and A/A/588/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link145
# link: A:A:P622 A:A:W588
cmd.dist("link146", "psg and A/A/622/CA", "psg and A/A/588/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link146
# link: A:A:A590 A:A:E592
cmd.dist("link147", "psg and A/A/590/CA", "psg and A/A/592/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link147
# link: A:A:A590 A:A:W606
cmd.dist("link148", "psg and A/A/590/CA", "psg and A/A/606/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link148
# link: A:A:A590 A:A:R666
cmd.dist("link149", "psg and A/A/590/CA", "psg and A/A/666/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link149
# link: A:A:E592 A:A:P663
cmd.dist("link150", "psg and A/A/592/CA", "psg and A/A/663/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link150
# link: A:A:E592 A:A:R666
cmd.dist("link151", "psg and A/A/592/CA", "psg and A/A/666/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link151
# link: A:A:F596 A:A:N595
cmd.dist("link152", "psg and A/A/596/CA", "psg and A/A/595/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link152
# link: A:A:R640 A:A:W606
cmd.dist("link153", "psg and A/A/640/CA", "psg and A/A/606/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link153
# link: A:A:W606 A:A:W659
cmd.dist("link154", "psg and A/A/606/CA", "psg and A/A/659/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link154
# link: A:A:R666 A:A:W606
cmd.dist("link155", "psg and A/A/666/CA", "psg and A/A/606/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link155
# link: A:A:F608 A:A:F669
cmd.dist("link156", "psg and A/A/608/CA", "psg and A/A/669/CA", label = 0, width = link_fixed_size_value)
color color_num_7, link156
# link: A:A:M617 A:A:W613
cmd.dist("link157", "psg and A/A/617/CA", "psg and A/A/613/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link157
# link: A:A:V620 A:A:W613
cmd.dist("link158", "psg and A/A/620/CA", "psg and A/A/613/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link158
# link: A:A:L641 A:A:W613
cmd.dist("link159", "psg and A/A/641/CA", "psg and A/A/613/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link159
# link: A:A:P644 A:A:W613
cmd.dist("link160", "psg and A/A/644/CA", "psg and A/A/613/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link160
# link: A:A:W613 A:A:W659
cmd.dist("link161", "psg and A/A/613/CA", "psg and A/A/659/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link161
# link: A:A:C647 A:A:L616
cmd.dist("link162", "psg and A/A/647/CA", "psg and A/A/616/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link162
# link: A:A:L616 A:A:L651
cmd.dist("link163", "psg and A/A/616/CA", "psg and A/A/651/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link163
# link: A:A:M617 A:A:V620
cmd.dist("link164", "psg and A/A/617/CA", "psg and A/A/620/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link164
# link: A:A:M617 A:A:P644
cmd.dist("link165", "psg and A/A/617/CA", "psg and A/A/644/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link165
# link: A:A:F623 A:A:P622
cmd.dist("link166", "psg and A/A/623/CA", "psg and A/A/622/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link166
# link: A:A:L641 A:A:P622
cmd.dist("link167", "psg and A/A/641/CA", "psg and A/A/622/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link167
# link: A:A:F623 A:A:L641
cmd.dist("link168", "psg and A/A/623/CA", "psg and A/A/641/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link168
# link: A:A:E636 A:A:Y661
cmd.dist("link169", "psg and A/A/636/CA", "psg and A/A/661/CA", label = 0, width = link_fixed_size_value)
color color_num_3, link169
# link: A:A:R640 A:A:W659
cmd.dist("link170", "psg and A/A/640/CA", "psg and A/A/659/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link170
# link: A:A:C647 A:A:P644
cmd.dist("link171", "psg and A/A/647/CA", "psg and A/A/644/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link171
# link: A:A:C647 A:A:P648
cmd.dist("link172", "psg and A/A/647/CA", "psg and A/A/648/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link172
# link: A:A:C647 A:A:L651
cmd.dist("link173", "psg and A/A/647/CA", "psg and A/A/651/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link173
# link: A:A:L651 A:A:P648
cmd.dist("link174", "psg and A/A/651/CA", "psg and A/A/648/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link174
# link: A:A:P663 A:A:R666
cmd.dist("link175", "psg and A/A/663/CA", "psg and A/A/666/CA", label = 0, width = link_fixed_size_value)
color color_num_2, link175
# link: A:A:A341 A:A:I302
cmd.dist("link176", "psg and A/A/341/CA", "psg and A/A/302/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link176
# link: A:A:A341 A:A:I359
cmd.dist("link177", "psg and A/A/341/CA", "psg and A/A/359/CA", label = 0, width = link_fixed_size_value)
color color_num_6, link177
# link: A:A:F433 A:A:Q432
cmd.dist("link178", "psg and A/A/433/CA", "psg and A/A/432/CA", label = 0, width = link_fixed_size_value)
color color_num_14, link178
# link: A:A:E572 A:A:F433
cmd.dist("link179", "psg and A/A/572/CA", "psg and A/A/433/CA", label = 0, width = link_fixed_size_value)
color color_num_14, link179
# node: A:A:F40
sele node1, psg and A/A/40/CA
color color_num_9, node1
alter node1, vdw = node_fixed_size_value
show sphere, node1

# node: A:A:K38
sele node2, psg and A/A/38/CA
color color_num_9, node2
alter node2, vdw = node_fixed_size_value
show sphere, node2

# node: A:A:A53
sele node3, psg and A/A/53/CA
color color_num_9, node3
alter node3, vdw = node_fixed_size_value
show sphere, node3

# node: A:A:E123
sele node4, psg and A/A/123/CA
color color_num_1, node4
alter node4, vdw = hub_fixed_size_value
show sphere, node4

# node: A:A:Y42
sele node5, psg and A/A/42/CA
color color_num_1, node5
alter node5, vdw = hub_fixed_size_value
show sphere, node5

# node: A:A:R125
sele node6, psg and A/A/125/CA
color color_num_1, node6
alter node6, vdw = hub_fixed_size_value
show sphere, node6

# node: A:A:F146
sele node7, psg and A/A/146/CA
color color_num_1, node7
alter node7, vdw = hub_fixed_size_value
show sphere, node7

# node: A:A:Q150
sele node8, psg and A/A/150/CA
color color_num_1, node8
alter node8, vdw = node_fixed_size_value
show sphere, node8

# node: A:A:F43
sele node9, psg and A/A/43/CA
color color_num_1, node9
alter node9, vdw = hub_fixed_size_value
show sphere, node9

# node: A:A:Y83
sele node10, psg and A/A/83/CA
color color_num_1, node10
alter node10, vdw = hub_fixed_size_value
show sphere, node10

# node: A:A:E44
sele node11, psg and A/A/44/CA
color color_num_3, node11
alter node11, vdw = node_fixed_size_value
show sphere, node11

# node: A:A:W52
sele node12, psg and A/A/52/CA
color color_num_3, node12
alter node12, vdw = hub_fixed_size_value
show sphere, node12

# node: A:A:Q149
sele node13, psg and A/A/149/CA
color color_num_3, node13
alter node13, vdw = hub_fixed_size_value
show sphere, node13

# node: A:A:R178
sele node14, psg and A/A/178/CA
color color_num_3, node14
alter node14, vdw = hub_fixed_size_value
show sphere, node14

# node: A:A:S45
sele node15, psg and A/A/45/CA
color color_num_3, node15
alter node15, vdw = node_fixed_size_value
show sphere, node15

# node: A:A:S47
sele node16, psg and A/A/47/CA
color color_num_3, node16
alter node16, vdw = hub_fixed_size_value
show sphere, node16

# node: A:A:V72
sele node17, psg and A/A/72/CA
color color_num_1, node17
alter node17, vdw = node_fixed_size_value
show sphere, node17

# node: A:A:V77
sele node18, psg and A/A/77/CA
color color_num_1, node18
alter node18, vdw = node_fixed_size_value
show sphere, node18

# node: A:A:T143
sele node19, psg and A/A/143/CA
color color_num_1, node19
alter node19, vdw = hub_fixed_size_value
show sphere, node19

# node: A:A:C82
sele node20, psg and A/A/82/CA
color color_num_1, node20
alter node20, vdw = node_fixed_size_value
show sphere, node20

# node: A:A:P130
sele node21, psg and A/A/130/CA
color color_num_1, node21
alter node21, vdw = node_fixed_size_value
show sphere, node21

# node: A:A:F137
sele node22, psg and A/A/137/CA
color color_num_1, node22
alter node22, vdw = hub_fixed_size_value
show sphere, node22

# node: A:A:L124
sele node23, psg and A/A/124/CA
color color_num_1, node23
alter node23, vdw = node_fixed_size_value
show sphere, node23

# node: A:A:I126
sele node24, psg and A/A/126/CA
color color_num_1, node24
alter node24, vdw = hub_fixed_size_value
show sphere, node24

# node: A:A:R86
sele node25, psg and A/A/86/CA
color color_num_1, node25
alter node25, vdw = hub_fixed_size_value
show sphere, node25

# node: A:A:W97
sele node26, psg and A/A/97/CA
color color_num_1, node26
alter node26, vdw = hub_fixed_size_value
show sphere, node26

# node: A:A:L87
sele node27, psg and A/A/87/CA
color color_num_5, node27
alter node27, vdw = hub_fixed_size_value
show sphere, node27

# node: A:A:Y111
sele node28, psg and A/A/111/CA
color color_num_5, node28
alter node28, vdw = hub_fixed_size_value
show sphere, node28

# node: A:A:W120
sele node29, psg and A/A/120/CA
color color_num_5, node29
alter node29, vdw = hub_fixed_size_value
show sphere, node29

# node: A:A:H115
sele node30, psg and A/A/115/CA
color color_num_5, node30
alter node30, vdw = node_fixed_size_value
show sphere, node30

# node: A:A:H89
sele node31, psg and A/A/89/CA
color color_num_5, node31
alter node31, vdw = hub_fixed_size_value
show sphere, node31

# node: A:A:E119
sele node32, psg and A/A/119/CA
color color_num_5, node32
alter node32, vdw = node_fixed_size_value
show sphere, node32

# node: A:A:R127
sele node33, psg and A/A/127/CA
color color_num_1, node33
alter node33, vdw = hub_fixed_size_value
show sphere, node33

# node: A:A:D342
sele node34, psg and A/A/342/CA
color color_num_1, node34
alter node34, vdw = node_fixed_size_value
show sphere, node34

# node: A:A:D345
sele node35, psg and A/A/345/CA
color color_num_6, node35
alter node35, vdw = hub_fixed_size_value
show sphere, node35

# node: A:A:H99
sele node36, psg and A/A/99/CA
color color_num_6, node36
alter node36, vdw = node_fixed_size_value
show sphere, node36

# node: A:A:S357
sele node37, psg and A/A/357/CA
color color_num_6, node37
alter node37, vdw = node_fixed_size_value
show sphere, node37

# node: A:A:F147
sele node38, psg and A/A/147/CA
color color_num_1, node38
alter node38, vdw = hub_fixed_size_value
show sphere, node38

# node: A:A:Y128
sele node39, psg and A/A/128/CA
color color_num_1, node39
alter node39, vdw = node_fixed_size_value
show sphere, node39

# node: A:A:E256
sele node40, psg and A/A/256/CA
color color_num_1, node40
alter node40, vdw = node_fixed_size_value
show sphere, node40

# node: A:A:L343
sele node41, psg and A/A/343/CA
color color_num_1, node41
alter node41, vdw = hub_fixed_size_value
show sphere, node41

# node: A:A:V151
sele node42, psg and A/A/151/CA
color color_num_1, node42
alter node42, vdw = node_fixed_size_value
show sphere, node42

# node: A:A:F244
sele node43, psg and A/A/244/CA
color color_num_1, node43
alter node43, vdw = hub_fixed_size_value
show sphere, node43

# node: A:A:Y148
sele node44, psg and A/A/148/CA
color color_num_3, node44
alter node44, vdw = hub_fixed_size_value
show sphere, node44

# node: A:A:K152
sele node45, psg and A/A/152/CA
color color_num_3, node45
alter node45, vdw = node_fixed_size_value
show sphere, node45

# node: A:A:E175
sele node46, psg and A/A/175/CA
color color_num_3, node46
alter node46, vdw = hub_fixed_size_value
show sphere, node46

# node: A:A:I240
sele node47, psg and A/A/240/CA
color color_num_3, node47
alter node47, vdw = hub_fixed_size_value
show sphere, node47

# node: A:A:F253
sele node48, psg and A/A/253/CA
color color_num_1, node48
alter node48, vdw = node_fixed_size_value
show sphere, node48

# node: A:A:K170
sele node49, psg and A/A/170/CA
color color_num_11, node49
alter node49, vdw = hub_fixed_size_value
show sphere, node49

# node: A:A:Q230
sele node50, psg and A/A/230/CA
color color_num_11, node50
alter node50, vdw = node_fixed_size_value
show sphere, node50

# node: A:A:F231
sele node51, psg and A/A/231/CA
color color_num_11, node51
alter node51, vdw = node_fixed_size_value
show sphere, node51

# node: A:A:S179
sele node52, psg and A/A/179/CA
color color_num_3, node52
alter node52, vdw = node_fixed_size_value
show sphere, node52

# node: A:A:Y180
sele node53, psg and A/A/180/CA
color color_num_3, node53
alter node53, vdw = hub_fixed_size_value
show sphere, node53

# node: A:A:R597
sele node54, psg and A/A/597/CA
color color_num_3, node54
alter node54, vdw = node_fixed_size_value
show sphere, node54

# node: A:A:F596
sele node55, psg and A/A/596/CA
color color_num_3, node55
alter node55, vdw = hub_fixed_size_value
show sphere, node55

# node: A:A:L188
sele node56, psg and A/A/188/CA
color color_num_3, node56
alter node56, vdw = node_fixed_size_value
show sphere, node56

# node: A:A:M183
sele node57, psg and A/A/183/CA
color color_num_3, node57
alter node57, vdw = node_fixed_size_value
show sphere, node57

# node: A:A:F228
sele node58, psg and A/A/228/CA
color color_num_3, node58
alter node58, vdw = hub_fixed_size_value
show sphere, node58

# node: A:A:N595
sele node59, psg and A/A/595/CA
color color_num_3, node59
alter node59, vdw = node_fixed_size_value
show sphere, node59

# node: A:A:K190
sele node60, psg and A/A/190/CA
color color_num_3, node60
alter node60, vdw = node_fixed_size_value
show sphere, node60

# node: A:A:N193
sele node61, psg and A/A/193/CA
color color_num_3, node61
alter node61, vdw = hub_fixed_size_value
show sphere, node61

# node: A:A:E636
sele node62, psg and A/A/636/CA
color color_num_3, node62
alter node62, vdw = node_fixed_size_value
show sphere, node62

# node: A:A:Y661
sele node63, psg and A/A/661/CA
color color_num_3, node63
alter node63, vdw = hub_fixed_size_value
show sphere, node63

# node: A:A:F207
sele node64, psg and A/A/207/CA
color color_num_10, node64
alter node64, vdw = hub_fixed_size_value
show sphere, node64

# node: A:A:P208
sele node65, psg and A/A/208/CA
color color_num_10, node65
alter node65, vdw = hub_fixed_size_value
show sphere, node65

# node: A:A:L211
sele node66, psg and A/A/211/CA
color color_num_10, node66
alter node66, vdw = hub_fixed_size_value
show sphere, node66

# node: A:A:C288
sele node67, psg and A/A/288/CA
color color_num_12, node67
alter node67, vdw = node_fixed_size_value
show sphere, node67

# node: A:A:D285
sele node68, psg and A/A/285/CA
color color_num_12, node68
alter node68, vdw = node_fixed_size_value
show sphere, node68

# node: A:A:N289
sele node69, psg and A/A/289/CA
color color_num_12, node69
alter node69, vdw = node_fixed_size_value
show sphere, node69

# node: A:A:I302
sele node70, psg and A/A/302/CA
color color_num_6, node70
alter node70, vdw = hub_fixed_size_value
show sphere, node70

# node: A:A:I359
sele node71, psg and A/A/359/CA
color color_num_6, node71
alter node71, vdw = hub_fixed_size_value
show sphere, node71

# node: A:A:E416
sele node72, psg and A/A/416/CA
color color_num_13, node72
alter node72, vdw = node_fixed_size_value
show sphere, node72

# node: A:A:T412
sele node73, psg and A/A/412/CA
color color_num_13, node73
alter node73, vdw = node_fixed_size_value
show sphere, node73

# node: A:A:T491
sele node74, psg and A/A/491/CA
color color_num_13, node74
alter node74, vdw = node_fixed_size_value
show sphere, node74

# node: A:A:I490
sele node75, psg and A/A/490/CA
color color_num_8, node75
alter node75, vdw = node_fixed_size_value
show sphere, node75

# node: A:A:R419
sele node76, psg and A/A/419/CA
color color_num_8, node76
alter node76, vdw = node_fixed_size_value
show sphere, node76

# node: A:A:W496
sele node77, psg and A/A/496/CA
color color_num_8, node77
alter node77, vdw = hub_fixed_size_value
show sphere, node77

# node: A:A:I453
sele node78, psg and A/A/453/CA
color color_num_8, node78
alter node78, vdw = node_fixed_size_value
show sphere, node78

# node: A:A:L424
sele node79, psg and A/A/424/CA
color color_num_8, node79
alter node79, vdw = node_fixed_size_value
show sphere, node79

# node: A:A:E572
sele node80, psg and A/A/572/CA
color color_num_14, node80
alter node80, vdw = node_fixed_size_value
show sphere, node80

# node: A:A:Q432
sele node81, psg and A/A/432/CA
color color_num_14, node81
alter node81, vdw = node_fixed_size_value
show sphere, node81

# node: A:A:E445
sele node82, psg and A/A/445/CA
color color_num_15, node82
alter node82, vdw = node_fixed_size_value
show sphere, node82

# node: A:A:S443
sele node83, psg and A/A/443/CA
color color_num_15, node83
alter node83, vdw = node_fixed_size_value
show sphere, node83

# node: A:A:N446
sele node84, psg and A/A/446/CA
color color_num_15, node84
alter node84, vdw = node_fixed_size_value
show sphere, node84

# node: A:A:F478
sele node85, psg and A/A/478/CA
color color_num_4, node85
alter node85, vdw = hub_fixed_size_value
show sphere, node85

# node: A:A:L537
sele node86, psg and A/A/537/CA
color color_num_4, node86
alter node86, vdw = hub_fixed_size_value
show sphere, node86

# node: A:A:F542
sele node87, psg and A/A/542/CA
color color_num_4, node87
alter node87, vdw = node_fixed_size_value
show sphere, node87

# node: A:A:F565
sele node88, psg and A/A/565/CA
color color_num_4, node88
alter node88, vdw = hub_fixed_size_value
show sphere, node88

# node: A:A:H480
sele node89, psg and A/A/480/CA
color color_num_4, node89
alter node89, vdw = hub_fixed_size_value
show sphere, node89

# node: A:A:P481
sele node90, psg and A/A/481/CA
color color_num_4, node90
alter node90, vdw = node_fixed_size_value
show sphere, node90

# node: A:A:H482
sele node91, psg and A/A/482/CA
color color_num_4, node91
alter node91, vdw = hub_fixed_size_value
show sphere, node91

# node: A:A:I483
sele node92, psg and A/A/483/CA
color color_num_4, node92
alter node92, vdw = node_fixed_size_value
show sphere, node92

# node: A:A:T532
sele node93, psg and A/A/532/CA
color color_num_4, node93
alter node93, vdw = hub_fixed_size_value
show sphere, node93

# node: A:A:F510
sele node94, psg and A/A/510/CA
color color_num_16, node94
alter node94, vdw = hub_fixed_size_value
show sphere, node94

# node: A:A:R514
sele node95, psg and A/A/514/CA
color color_num_16, node95
alter node95, vdw = hub_fixed_size_value
show sphere, node95

# node: A:A:L518
sele node96, psg and A/A/518/CA
color color_num_16, node96
alter node96, vdw = node_fixed_size_value
show sphere, node96

# node: A:A:I547
sele node97, psg and A/A/547/CA
color color_num_7, node97
alter node97, vdw = node_fixed_size_value
show sphere, node97

# node: A:A:L534
sele node98, psg and A/A/534/CA
color color_num_7, node98
alter node98, vdw = node_fixed_size_value
show sphere, node98

# node: A:A:F608
sele node99, psg and A/A/608/CA
color color_num_7, node99
alter node99, vdw = hub_fixed_size_value
show sphere, node99

# node: A:A:F669
sele node100, psg and A/A/669/CA
color color_num_7, node100
alter node100, vdw = hub_fixed_size_value
show sphere, node100

# node: A:A:H544
sele node101, psg and A/A/544/CA
color color_num_7, node101
alter node101, vdw = hub_fixed_size_value
show sphere, node101

# node: A:A:D604
sele node102, psg and A/A/604/CA
color color_num_7, node102
alter node102, vdw = node_fixed_size_value
show sphere, node102

# node: A:A:D546
sele node103, psg and A/A/546/CA
color color_num_2, node103
alter node103, vdw = node_fixed_size_value
show sphere, node103

# node: A:A:R550
sele node104, psg and A/A/550/CA
color color_num_2, node104
alter node104, vdw = hub_fixed_size_value
show sphere, node104

# node: A:A:N551
sele node105, psg and A/A/551/CA
color color_num_2, node105
alter node105, vdw = node_fixed_size_value
show sphere, node105

# node: A:A:A548
sele node106, psg and A/A/548/CA
color color_num_2, node106
alter node106, vdw = node_fixed_size_value
show sphere, node106

# node: A:A:W588
sele node107, psg and A/A/588/CA
color color_num_2, node107
alter node107, vdw = hub_fixed_size_value
show sphere, node107

# node: A:A:P585
sele node108, psg and A/A/585/CA
color color_num_2, node108
alter node108, vdw = node_fixed_size_value
show sphere, node108

# node: A:A:P622
sele node109, psg and A/A/622/CA
color color_num_2, node109
alter node109, vdw = node_fixed_size_value
show sphere, node109

# node: A:A:A590
sele node110, psg and A/A/590/CA
color color_num_2, node110
alter node110, vdw = node_fixed_size_value
show sphere, node110

# node: A:A:E592
sele node111, psg and A/A/592/CA
color color_num_2, node111
alter node111, vdw = node_fixed_size_value
show sphere, node111

# node: A:A:W606
sele node112, psg and A/A/606/CA
color color_num_2, node112
alter node112, vdw = hub_fixed_size_value
show sphere, node112

# node: A:A:R666
sele node113, psg and A/A/666/CA
color color_num_2, node113
alter node113, vdw = hub_fixed_size_value
show sphere, node113

# node: A:A:P663
sele node114, psg and A/A/663/CA
color color_num_2, node114
alter node114, vdw = node_fixed_size_value
show sphere, node114

# node: A:A:R640
sele node115, psg and A/A/640/CA
color color_num_2, node115
alter node115, vdw = node_fixed_size_value
show sphere, node115

# node: A:A:W659
sele node116, psg and A/A/659/CA
color color_num_2, node116
alter node116, vdw = hub_fixed_size_value
show sphere, node116

# node: A:A:M617
sele node117, psg and A/A/617/CA
color color_num_2, node117
alter node117, vdw = node_fixed_size_value
show sphere, node117

# node: A:A:W613
sele node118, psg and A/A/613/CA
color color_num_2, node118
alter node118, vdw = hub_fixed_size_value
show sphere, node118

# node: A:A:V620
sele node119, psg and A/A/620/CA
color color_num_2, node119
alter node119, vdw = node_fixed_size_value
show sphere, node119

# node: A:A:L641
sele node120, psg and A/A/641/CA
color color_num_2, node120
alter node120, vdw = hub_fixed_size_value
show sphere, node120

# node: A:A:P644
sele node121, psg and A/A/644/CA
color color_num_2, node121
alter node121, vdw = node_fixed_size_value
show sphere, node121

# node: A:A:C647
sele node122, psg and A/A/647/CA
color color_num_2, node122
alter node122, vdw = hub_fixed_size_value
show sphere, node122

# node: A:A:L616
sele node123, psg and A/A/616/CA
color color_num_2, node123
alter node123, vdw = node_fixed_size_value
show sphere, node123

# node: A:A:L651
sele node124, psg and A/A/651/CA
color color_num_2, node124
alter node124, vdw = node_fixed_size_value
show sphere, node124

# node: A:A:F623
sele node125, psg and A/A/623/CA
color color_num_2, node125
alter node125, vdw = hub_fixed_size_value
show sphere, node125

# node: A:A:P648
sele node126, psg and A/A/648/CA
color color_num_2, node126
alter node126, vdw = node_fixed_size_value
show sphere, node126

# node: A:A:A341
sele node127, psg and A/A/341/CA
color color_num_6, node127
alter node127, vdw = node_fixed_size_value
show sphere, node127

# node: A:A:F433
sele node128, psg and A/A/433/CA
color color_num_14, node128
alter node128, vdw = node_fixed_size_value
show sphere, node128

