# pml automagically-generated by psntools 1.0

# molecule file name, you can change it with an other file of the same molecule
mol_file_name = "hFAK1_2j0j_al_yl2_1.pdb"

# cartoon color definition, change it as you please
set_color cartoon_color, [ 0.60, 0.60, 0.60 ]

# color definitions, change them as you please
set_color color_value_from_0_to_10,   [ 0.00, 0.00, 0.00 ]
set_color color_value_from_10_to_20,  [ 0.10, 0.10, 0.10 ]
set_color color_value_from_20_to_30,  [ 0.30, 0.30, 0.30 ]
set_color color_value_from_30_to_40,  [ 0.60, 0.60, 0.60 ]
set_color color_value_from_40_to_50,  [ 0.00, 0.00, 1.00 ]
set_color color_value_from_50_to_60,  [ 0.00, 0.50, 1.00 ]
set_color color_value_from_60_to_70,  [ 0.00, 1.00, 0.00 ]
set_color color_value_from_70_to_80,  [ 1.00, 1.00, 0.00 ]
set_color color_value_from_80_to_90,  [ 1.00, 0.60, 0.00 ]
set_color color_value_from_90_to_100, [ 1.00, 0.00, 0.00 ]

# color definitions, change them as you please
set_color color_num_0,   [ 0.00, 0.00, 0.00 ]
set_color color_num_1,   [ 1.00, 0.00, 0.00 ]
set_color color_num_2,   [ 0.00, 1.00, 0.00 ]
set_color color_num_3,   [ 0.00, 0.00, 1.00 ]
set_color color_num_4,   [ 1.00, 1.00, 0.00 ]
set_color color_num_5,   [ 0.00, 1.00, 1.00 ]
set_color color_num_6,   [ 1.00, 0.00, 1.00 ]
set_color color_num_7,   [ 0.80, 1.00, 0.00 ]
set_color color_num_8,   [ 1.00, 0.70, 0.70 ]
set_color color_num_9,   [ 1.00, 0.70, 0.20 ]
set_color color_num_10,  [ 0.00, 0.60, 1.00 ]
set_color color_num_11,  [ 0.54, 0.31, 0.64 ]
set_color color_num_12,  [ 1.00, 0.50, 1.00 ]
set_color color_num_13,  [ 0.20, 0.60, 0.20 ]
set_color color_num_14,  [ 1.00, 0.12, 0.00 ]
set_color color_num_15,  [ 1.00, 0.24, 0.00 ]
set_color color_num_16,  [ 1.00, 0.36, 0.00 ]
set_color color_num_17,  [ 1.00, 0.48, 0.00 ]
set_color color_num_18,  [ 1.00, 0.60, 0.00 ]
set_color color_num_19,  [ 1.00, 0.72, 0.00 ]
set_color color_num_20,  [ 1.00, 0.84, 0.00 ]
set_color color_num_21,  [ 1.00, 0.96, 0.00 ]
set_color color_num_22,  [ 0.92, 1.00, 0.00 ]
set_color color_num_23,  [ 0.80, 1.00, 0.00 ]
set_color color_num_24,  [ 0.68, 1.00, 0.00 ]
set_color color_num_25,  [ 0.56, 1.00, 0.00 ]
set_color color_num_26,  [ 0.44, 1.00, 0.00 ]
set_color color_num_27,  [ 0.32, 1.00, 0.00 ]
set_color color_num_28,  [ 0.20, 1.00, 0.00 ]
set_color color_num_29,  [ 0.08, 1.00, 0.00 ]
set_color color_num_30,  [ 0.00, 1.00, 0.04 ]
set_color color_num_31,  [ 0.00, 1.00, 0.16 ]
set_color color_num_32,  [ 0.00, 1.00, 0.28 ]
set_color color_num_33,  [ 0.00, 1.00, 0.40 ]
set_color color_num_34,  [ 0.00, 1.00, 0.52 ]
set_color color_num_35,  [ 0.00, 1.00, 0.64 ]
set_color color_num_36,  [ 0.00, 1.00, 0.76 ]
set_color color_num_37,  [ 0.00, 1.00, 0.88 ]
set_color color_num_38,  [ 0.00, 1.00, 1.00 ]
set_color color_num_39,  [ 0.00, 0.88, 1.00 ]
set_color color_num_40,  [ 0.00, 0.76, 1.00 ]
set_color color_num_41,  [ 0.00, 0.64, 1.00 ]
set_color color_num_42,  [ 0.00, 0.52, 1.00 ]
set_color color_num_43,  [ 0.00, 0.40, 1.00 ]
set_color color_num_44,  [ 0.00, 0.28, 1.00 ]
set_color color_num_45,  [ 0.00, 0.16, 1.00 ]
set_color color_num_46,  [ 0.00, 0.04, 1.00 ]
set_color color_num_47,  [ 0.08, 0.00, 1.00 ]
set_color color_num_48,  [ 0.20, 0.00, 1.00 ]
set_color color_num_49,  [ 0.32, 0.00, 1.00 ]
set_color color_num_50,  [ 0.44, 0.00, 1.00 ]
set_color color_num_51,  [ 0.56, 0.00, 1.00 ]
set_color color_num_52,  [ 0.68, 0.00, 1.00 ]
set_color color_num_53,  [ 0.80, 0.00, 1.00 ]
set_color color_num_54,  [ 0.92, 0.00, 1.00 ]
set_color color_num_55,  [ 1.00, 0.00, 0.96 ]
set_color color_num_56,  [ 1.00, 0.00, 0.84 ]
set_color color_num_57,  [ 1.00, 0.00, 0.72 ]
set_color color_num_58,  [ 1.00, 0.00, 0.60 ]
set_color color_num_59,  [ 1.00, 0.00, 0.48 ]
set_color color_num_60,  [ 1.00, 0.00, 0.36 ]
set_color color_num_61,  [ 1.00, 0.00, 0.24 ]
set_color color_num_62,  [ 1.00, 0.00, 0.12 ]

# fixed size radius used for clusters and communities, change them as you please
link_fixed_size_value = 4.0
node_fixed_size_value = 1.0
hub_fixed_size_value  = 1.8

# link size definitions, change them as you please
link_size_value_from_0_to_10   = 2.5
link_size_value_from_10_to_20  = 3.0
link_size_value_from_20_to_30  = 3.5
link_size_value_from_30_to_40  = 4.0
link_size_value_from_40_to_50  = 4.5
link_size_value_from_50_to_60  = 5.0
link_size_value_from_60_to_70  = 5.5
link_size_value_from_70_to_80  = 6.0
link_size_value_from_80_to_90  = 6.5
link_size_value_from_90_to_100 = 7.0

# node size definitions, change them as you please
node_size_value_from_0_to_10   = 0.5
node_size_value_from_10_to_20  = 0.6
node_size_value_from_20_to_30  = 0.7
node_size_value_from_30_to_40  = 0.8
node_size_value_from_40_to_50  = 0.9
node_size_value_from_50_to_60  = 1.0
node_size_value_from_60_to_70  = 1.1
node_size_value_from_70_to_80  = 1.2
node_size_value_from_80_to_90  = 1.3
node_size_value_from_90_to_100 = 1.4

# diff colors definitions, change them as you please
set_color net1_items_color,   [ 1.0, 0.5, 0.0 ]
set_color shared_items_color, [ 0.5, 1.0, 0.0 ]
set_color net2_items_color,   [ 0.8, 0.5, 1.0 ]

# pert colors definitions, change them as you please
set_color color_pert_neg_75_100, [ 0.00, 0.00, 1.00 ]
set_color color_pert_neg_50_75,  [ 0.00, 0.37, 1.00 ]
set_color color_pert_neg_25_50,  [ 0.00, 0.75, 1.00 ]
set_color color_pert_neg_0_25,   [ 0.00, 1.00, 1.00 ]
set_color color_pert_zero,       [ 1.00, 1.00, 1.00 ]
set_color color_pert_pos_75_100, [ 1.00, 0.00, 0.00 ]
set_color color_pert_pos_50_75,  [ 1.00, 0.37, 0.00 ]
set_color color_pert_pos_25_50,  [ 1.00, 0.75, 0.00 ]
set_color color_pert_pos_0_25,   [ 1.00, 1.00, 0.00 ]

# some other graphic settings, change them as you please
cartoon automatic
set cartoon_smooth_loops=0
set cartoon_fancy_helices=1
set transparency_mode=1
set ray_shadows=0
set ray_transparency_shadows=0
set cartoon_transparency=0.6
bg_color white
set ortho=on
set depth_cue=off
set ray_trace_fog=0
set antialias=1
set dash_gap,0.0
set dash_round_ends,on
set dash_width,3.0
set dash_radius,0.0
print("this is PSN_hubs.pml")



# =========================================== #
# PLEASE DO NOT EDIT ANYTHING BELOW THIS LINE #
# =========================================== #



cmd.load(mol_file_name, "molcart")
dss molcart
hide everything, molcart
color cartoon_color, molcart
show cartoon, molcart

sele notpol, molcart and not polymer
show sticks, notpol
cmd.load(mol_file_name, "psg")
hide everything, psg
# node: A:A:Y42
sele node1, psg and A/A/42/CA
color color_value_from_70_to_80, node1
alter node1, vdw = node_size_value_from_70_to_80
show sphere, node1

# node: A:A:F43
sele node2, psg and A/A/43/CA
color color_value_from_90_to_100, node2
alter node2, vdw = node_size_value_from_90_to_100
show sphere, node2

# node: A:A:S47
sele node3, psg and A/A/47/CA
color color_value_from_40_to_50, node3
alter node3, vdw = node_size_value_from_40_to_50
show sphere, node3

# node: A:A:W52
sele node4, psg and A/A/52/CA
color color_value_from_60_to_70, node4
alter node4, vdw = node_size_value_from_60_to_70
show sphere, node4

# node: A:A:Y83
sele node5, psg and A/A/83/CA
color color_value_from_80_to_90, node5
alter node5, vdw = node_size_value_from_80_to_90
show sphere, node5

# node: A:A:F85
sele node6, psg and A/A/85/CA
color color_value_from_70_to_80, node6
alter node6, vdw = node_size_value_from_70_to_80
show sphere, node6

# node: A:A:R86
sele node7, psg and A/A/86/CA
color color_value_from_90_to_100, node7
alter node7, vdw = node_size_value_from_90_to_100
show sphere, node7

# node: A:A:L87
sele node8, psg and A/A/87/CA
color color_value_from_80_to_90, node8
alter node8, vdw = node_size_value_from_80_to_90
show sphere, node8

# node: A:A:H89
sele node9, psg and A/A/89/CA
color color_value_from_90_to_100, node9
alter node9, vdw = node_size_value_from_90_to_100
show sphere, node9

# node: A:A:W97
sele node10, psg and A/A/97/CA
color color_value_from_90_to_100, node10
alter node10, vdw = node_size_value_from_90_to_100
show sphere, node10

# node: A:A:Y111
sele node11, psg and A/A/111/CA
color color_value_from_90_to_100, node11
alter node11, vdw = node_size_value_from_90_to_100
show sphere, node11

# node: A:A:W120
sele node12, psg and A/A/120/CA
color color_value_from_80_to_90, node12
alter node12, vdw = node_size_value_from_80_to_90
show sphere, node12

# node: A:A:E123
sele node13, psg and A/A/123/CA
color color_value_from_70_to_80, node13
alter node13, vdw = node_size_value_from_70_to_80
show sphere, node13

# node: A:A:R125
sele node14, psg and A/A/125/CA
color color_value_from_90_to_100, node14
alter node14, vdw = node_size_value_from_90_to_100
show sphere, node14

# node: A:A:I126
sele node15, psg and A/A/126/CA
color color_value_from_80_to_90, node15
alter node15, vdw = node_size_value_from_80_to_90
show sphere, node15

# node: A:A:R127
sele node16, psg and A/A/127/CA
color color_value_from_90_to_100, node16
alter node16, vdw = node_size_value_from_90_to_100
show sphere, node16

# node: A:A:F137
sele node17, psg and A/A/137/CA
color color_value_from_60_to_70, node17
alter node17, vdw = node_size_value_from_60_to_70
show sphere, node17

# node: A:A:D140
sele node18, psg and A/A/140/CA
color color_value_from_90_to_100, node18
alter node18, vdw = node_size_value_from_90_to_100
show sphere, node18

# node: A:A:T143
sele node19, psg and A/A/143/CA
color color_value_from_90_to_100, node19
alter node19, vdw = node_size_value_from_90_to_100
show sphere, node19

# node: A:A:F146
sele node20, psg and A/A/146/CA
color color_value_from_90_to_100, node20
alter node20, vdw = node_size_value_from_90_to_100
show sphere, node20

# node: A:A:F147
sele node21, psg and A/A/147/CA
color color_value_from_60_to_70, node21
alter node21, vdw = node_size_value_from_60_to_70
show sphere, node21

# node: A:A:Y148
sele node22, psg and A/A/148/CA
color color_value_from_90_to_100, node22
alter node22, vdw = node_size_value_from_90_to_100
show sphere, node22

# node: A:A:Q149
sele node23, psg and A/A/149/CA
color color_value_from_70_to_80, node23
alter node23, vdw = node_size_value_from_70_to_80
show sphere, node23

# node: A:A:K170
sele node24, psg and A/A/170/CA
color color_value_from_50_to_60, node24
alter node24, vdw = node_size_value_from_50_to_60
show sphere, node24

# node: A:A:E175
sele node25, psg and A/A/175/CA
color color_value_from_90_to_100, node25
alter node25, vdw = node_size_value_from_90_to_100
show sphere, node25

# node: A:A:R178
sele node26, psg and A/A/178/CA
color color_value_from_80_to_90, node26
alter node26, vdw = node_size_value_from_80_to_90
show sphere, node26

# node: A:A:Y180
sele node27, psg and A/A/180/CA
color color_value_from_70_to_80, node27
alter node27, vdw = node_size_value_from_70_to_80
show sphere, node27

# node: A:A:N193
sele node28, psg and A/A/193/CA
color color_value_from_70_to_80, node28
alter node28, vdw = node_size_value_from_70_to_80
show sphere, node28

# node: A:A:F206
sele node29, psg and A/A/206/CA
color color_value_from_60_to_70, node29
alter node29, vdw = node_size_value_from_60_to_70
show sphere, node29

# node: A:A:F207
sele node30, psg and A/A/207/CA
color color_value_from_40_to_50, node30
alter node30, vdw = node_size_value_from_40_to_50
show sphere, node30

# node: A:A:P208
sele node31, psg and A/A/208/CA
color color_value_from_40_to_50, node31
alter node31, vdw = node_size_value_from_40_to_50
show sphere, node31

# node: A:A:L211
sele node32, psg and A/A/211/CA
color color_value_from_40_to_50, node32
alter node32, vdw = node_size_value_from_40_to_50
show sphere, node32

# node: A:A:F228
sele node33, psg and A/A/228/CA
color color_value_from_40_to_50, node33
alter node33, vdw = node_size_value_from_40_to_50
show sphere, node33

# node: A:A:I240
sele node34, psg and A/A/240/CA
color color_value_from_70_to_80, node34
alter node34, vdw = node_size_value_from_70_to_80
show sphere, node34

# node: A:A:F244
sele node35, psg and A/A/244/CA
color color_value_from_60_to_70, node35
alter node35, vdw = node_size_value_from_60_to_70
show sphere, node35

# node: A:A:F296
sele node36, psg and A/A/296/CA
color color_value_from_90_to_100, node36
alter node36, vdw = node_size_value_from_90_to_100
show sphere, node36

# node: A:A:I302
sele node37, psg and A/A/302/CA
color color_value_from_30_to_40, node37
alter node37, vdw = node_size_value_from_30_to_40
show sphere, node37

# node: A:A:L343
sele node38, psg and A/A/343/CA
color color_value_from_90_to_100, node38
alter node38, vdw = node_size_value_from_90_to_100
show sphere, node38

# node: A:A:D345
sele node39, psg and A/A/345/CA
color color_value_from_50_to_60, node39
alter node39, vdw = node_size_value_from_50_to_60
show sphere, node39

# node: A:A:F358
sele node40, psg and A/A/358/CA
color color_value_from_60_to_70, node40
alter node40, vdw = node_size_value_from_60_to_70
show sphere, node40

# node: A:A:I359
sele node41, psg and A/A/359/CA
color color_value_from_40_to_50, node41
alter node41, vdw = node_size_value_from_40_to_50
show sphere, node41

# node: A:A:F478
sele node42, psg and A/A/478/CA
color color_value_from_40_to_50, node42
alter node42, vdw = node_size_value_from_40_to_50
show sphere, node42

# node: A:A:H480
sele node43, psg and A/A/480/CA
color color_value_from_90_to_100, node43
alter node43, vdw = node_size_value_from_90_to_100
show sphere, node43

# node: A:A:H482
sele node44, psg and A/A/482/CA
color color_value_from_80_to_90, node44
alter node44, vdw = node_size_value_from_80_to_90
show sphere, node44

# node: A:A:W496
sele node45, psg and A/A/496/CA
color color_value_from_70_to_80, node45
alter node45, vdw = node_size_value_from_70_to_80
show sphere, node45

# node: A:A:I497
sele node46, psg and A/A/497/CA
color color_value_from_40_to_50, node46
alter node46, vdw = node_size_value_from_40_to_50
show sphere, node46

# node: A:A:I498
sele node47, psg and A/A/498/CA
color color_value_from_50_to_60, node47
alter node47, vdw = node_size_value_from_50_to_60
show sphere, node47

# node: A:A:F510
sele node48, psg and A/A/510/CA
color color_value_from_70_to_80, node48
alter node48, vdw = node_size_value_from_70_to_80
show sphere, node48

# node: A:A:R514
sele node49, psg and A/A/514/CA
color color_value_from_80_to_90, node49
alter node49, vdw = node_size_value_from_80_to_90
show sphere, node49

# node: A:A:T532
sele node50, psg and A/A/532/CA
color color_value_from_60_to_70, node50
alter node50, vdw = node_size_value_from_60_to_70
show sphere, node50

# node: A:A:L537
sele node51, psg and A/A/537/CA
color color_value_from_50_to_60, node51
alter node51, vdw = node_size_value_from_50_to_60
show sphere, node51

# node: A:A:H544
sele node52, psg and A/A/544/CA
color color_value_from_50_to_60, node52
alter node52, vdw = node_size_value_from_50_to_60
show sphere, node52

# node: A:A:R550
sele node53, psg and A/A/550/CA
color color_value_from_80_to_90, node53
alter node53, vdw = node_size_value_from_80_to_90
show sphere, node53

# node: A:A:F565
sele node54, psg and A/A/565/CA
color color_value_from_50_to_60, node54
alter node54, vdw = node_size_value_from_50_to_60
show sphere, node54

# node: A:A:R569
sele node55, psg and A/A/569/CA
color color_value_from_70_to_80, node55
alter node55, vdw = node_size_value_from_70_to_80
show sphere, node55

# node: A:A:W588
sele node56, psg and A/A/588/CA
color color_value_from_70_to_80, node56
alter node56, vdw = node_size_value_from_70_to_80
show sphere, node56

# node: A:A:F596
sele node57, psg and A/A/596/CA
color color_value_from_70_to_80, node57
alter node57, vdw = node_size_value_from_70_to_80
show sphere, node57

# node: A:A:W606
sele node58, psg and A/A/606/CA
color color_value_from_70_to_80, node58
alter node58, vdw = node_size_value_from_70_to_80
show sphere, node58

# node: A:A:F608
sele node59, psg and A/A/608/CA
color color_value_from_60_to_70, node59
alter node59, vdw = node_size_value_from_60_to_70
show sphere, node59

# node: A:A:W613
sele node60, psg and A/A/613/CA
color color_value_from_90_to_100, node60
alter node60, vdw = node_size_value_from_90_to_100
show sphere, node60

# node: A:A:F623
sele node61, psg and A/A/623/CA
color color_value_from_90_to_100, node61
alter node61, vdw = node_size_value_from_90_to_100
show sphere, node61

# node: A:A:L641
sele node62, psg and A/A/641/CA
color color_value_from_90_to_100, node62
alter node62, vdw = node_size_value_from_90_to_100
show sphere, node62

# node: A:A:C647
sele node63, psg and A/A/647/CA
color color_value_from_60_to_70, node63
alter node63, vdw = node_size_value_from_60_to_70
show sphere, node63

# node: A:A:W659
sele node64, psg and A/A/659/CA
color color_value_from_70_to_80, node64
alter node64, vdw = node_size_value_from_70_to_80
show sphere, node64

# node: A:A:Y661
sele node65, psg and A/A/661/CA
color color_value_from_80_to_90, node65
alter node65, vdw = node_size_value_from_80_to_90
show sphere, node65

# node: A:A:D662
sele node66, psg and A/A/662/CA
color color_value_from_70_to_80, node66
alter node66, vdw = node_size_value_from_70_to_80
show sphere, node66

# node: A:A:R666
sele node67, psg and A/A/666/CA
color color_value_from_60_to_70, node67
alter node67, vdw = node_size_value_from_60_to_70
show sphere, node67

# node: A:A:F669
sele node68, psg and A/A/669/CA
color color_value_from_90_to_100, node68
alter node68, vdw = node_size_value_from_90_to_100
show sphere, node68

