# pml automagically-generated by psntools 0.1b

# molecule file name, you can change it with an other file of the same molecule
mol_file_name = "hFAK1_2j0j_al_yl2_1.pdb"

# cartoon color definition, change it as you please
set_color cartoon_color, [ 0.60, 0.60, 0.60 ]

# color definitions, change them as you please
set_color color_value_from_0_to_10,   [ 0.00, 0.00, 0.00 ]
set_color color_value_from_10_to_20,  [ 0.10, 0.10, 0.10 ]
set_color color_value_from_20_to_30,  [ 0.30, 0.30, 0.30 ]
set_color color_value_from_30_to_40,  [ 0.60, 0.60, 0.60 ]
set_color color_value_from_40_to_50,  [ 0.00, 0.00, 1.00 ]
set_color color_value_from_50_to_60,  [ 0.00, 0.50, 1.00 ]
set_color color_value_from_60_to_70,  [ 0.00, 1.00, 0.00 ]
set_color color_value_from_70_to_80,  [ 1.00, 1.00, 0.00 ]
set_color color_value_from_80_to_90,  [ 1.00, 0.60, 0.00 ]
set_color color_value_from_90_to_100, [ 1.00, 0.00, 0.00 ]

# color definitions, change them as you please
set_color color_num_0,   [ 0.00, 0.00, 0.00 ]
set_color color_num_1,   [ 1.00, 0.00, 0.00 ]
set_color color_num_2,   [ 0.00, 1.00, 0.00 ]
set_color color_num_3,   [ 0.00, 0.00, 1.00 ]
set_color color_num_4,   [ 1.00, 1.00, 0.00 ]
set_color color_num_5,   [ 0.00, 1.00, 1.00 ]
set_color color_num_6,   [ 1.00, 0.00, 1.00 ]
set_color color_num_7,   [ 0.80, 1.00, 0.00 ]
set_color color_num_8,   [ 1.00, 0.70, 0.70 ]
set_color color_num_9,   [ 1.00, 0.70, 0.20 ]
set_color color_num_10,  [ 0.00, 0.60, 1.00 ]
set_color color_num_11,  [ 0.54, 0.31, 0.64 ]
set_color color_num_12,  [ 1.00, 0.50, 1.00 ]
set_color color_num_13,  [ 0.20, 0.60, 0.20 ]
set_color color_num_14,  [ 1.00, 0.12, 0.00 ]
set_color color_num_15,  [ 1.00, 0.24, 0.00 ]
set_color color_num_16,  [ 1.00, 0.36, 0.00 ]
set_color color_num_17,  [ 1.00, 0.48, 0.00 ]
set_color color_num_18,  [ 1.00, 0.60, 0.00 ]
set_color color_num_19,  [ 1.00, 0.72, 0.00 ]
set_color color_num_20,  [ 1.00, 0.84, 0.00 ]
set_color color_num_21,  [ 1.00, 0.96, 0.00 ]
set_color color_num_22,  [ 0.92, 1.00, 0.00 ]
set_color color_num_23,  [ 0.80, 1.00, 0.00 ]
set_color color_num_24,  [ 0.68, 1.00, 0.00 ]
set_color color_num_25,  [ 0.56, 1.00, 0.00 ]
set_color color_num_26,  [ 0.44, 1.00, 0.00 ]
set_color color_num_27,  [ 0.32, 1.00, 0.00 ]
set_color color_num_28,  [ 0.20, 1.00, 0.00 ]
set_color color_num_29,  [ 0.08, 1.00, 0.00 ]
set_color color_num_30,  [ 0.00, 1.00, 0.04 ]
set_color color_num_31,  [ 0.00, 1.00, 0.16 ]
set_color color_num_32,  [ 0.00, 1.00, 0.28 ]
set_color color_num_33,  [ 0.00, 1.00, 0.40 ]
set_color color_num_34,  [ 0.00, 1.00, 0.52 ]
set_color color_num_35,  [ 0.00, 1.00, 0.64 ]
set_color color_num_36,  [ 0.00, 1.00, 0.76 ]
set_color color_num_37,  [ 0.00, 1.00, 0.88 ]
set_color color_num_38,  [ 0.00, 1.00, 1.00 ]
set_color color_num_39,  [ 0.00, 0.88, 1.00 ]
set_color color_num_40,  [ 0.00, 0.76, 1.00 ]
set_color color_num_41,  [ 0.00, 0.64, 1.00 ]
set_color color_num_42,  [ 0.00, 0.52, 1.00 ]
set_color color_num_43,  [ 0.00, 0.40, 1.00 ]
set_color color_num_44,  [ 0.00, 0.28, 1.00 ]
set_color color_num_45,  [ 0.00, 0.16, 1.00 ]
set_color color_num_46,  [ 0.00, 0.04, 1.00 ]
set_color color_num_47,  [ 0.08, 0.00, 1.00 ]
set_color color_num_48,  [ 0.20, 0.00, 1.00 ]
set_color color_num_49,  [ 0.32, 0.00, 1.00 ]
set_color color_num_50,  [ 0.44, 0.00, 1.00 ]
set_color color_num_51,  [ 0.56, 0.00, 1.00 ]
set_color color_num_52,  [ 0.68, 0.00, 1.00 ]
set_color color_num_53,  [ 0.80, 0.00, 1.00 ]
set_color color_num_54,  [ 0.92, 0.00, 1.00 ]
set_color color_num_55,  [ 1.00, 0.00, 0.96 ]
set_color color_num_56,  [ 1.00, 0.00, 0.84 ]
set_color color_num_57,  [ 1.00, 0.00, 0.72 ]
set_color color_num_58,  [ 1.00, 0.00, 0.60 ]
set_color color_num_59,  [ 1.00, 0.00, 0.48 ]
set_color color_num_60,  [ 1.00, 0.00, 0.36 ]
set_color color_num_61,  [ 1.00, 0.00, 0.24 ]
set_color color_num_62,  [ 1.00, 0.00, 0.12 ]

# fixed size radius used for clusters and communities, change them as you please
link_fixed_size_value = 4.0
node_fixed_size_value = 1.0
hub_fixed_size_value  = 1.8

# link size definitions, change them as you please
link_size_value_from_0_to_10   = 2.5
link_size_value_from_10_to_20  = 3.0
link_size_value_from_20_to_30  = 3.5
link_size_value_from_30_to_40  = 4.0
link_size_value_from_40_to_50  = 4.5
link_size_value_from_50_to_60  = 5.0
link_size_value_from_60_to_70  = 5.5
link_size_value_from_70_to_80  = 6.0
link_size_value_from_80_to_90  = 6.5
link_size_value_from_90_to_100 = 7.0

# node size definitions, change them as you please
node_size_value_from_0_to_10   = 0.5
node_size_value_from_10_to_20  = 0.6
node_size_value_from_20_to_30  = 0.7
node_size_value_from_30_to_40  = 0.8
node_size_value_from_40_to_50  = 0.9
node_size_value_from_50_to_60  = 1.0
node_size_value_from_60_to_70  = 1.1
node_size_value_from_70_to_80  = 1.2
node_size_value_from_80_to_90  = 1.3
node_size_value_from_90_to_100 = 1.4

# diff colors definitions, change them as you please
set_color net1_items_color,   [ 1.0, 0.5, 0.0 ]
set_color shared_items_color, [ 0.5, 1.0, 0.0 ]
set_color net2_items_color,   [ 0.8, 0.5, 1.0 ]

# pert colors definitions, change them as you please
set_color color_pert_neg_75_100, [ 0.00, 0.00, 1.00 ]
set_color color_pert_neg_50_75,  [ 0.00, 0.37, 1.00 ]
set_color color_pert_neg_25_50,  [ 0.00, 0.75, 1.00 ]
set_color color_pert_neg_0_25,   [ 0.00, 1.00, 1.00 ]
set_color color_pert_zero,       [ 1.00, 1.00, 1.00 ]
set_color color_pert_pos_75_100, [ 1.00, 0.00, 0.00 ]
set_color color_pert_pos_50_75,  [ 1.00, 0.37, 0.00 ]
set_color color_pert_pos_25_50,  [ 1.00, 0.75, 0.00 ]
set_color color_pert_pos_0_25,   [ 1.00, 1.00, 0.00 ]

# some other graphic settings, change them as you please
cartoon automatic
set cartoon_smooth_loops=0
set cartoon_fancy_helices=1
set transparency_mode=1
set ray_shadows=0
set ray_transparency_shadows=0
set cartoon_transparency=0.6
bg_color white
set ortho=on
set depth_cue=off
set ray_trace_fog=0
set antialias=1
set dash_gap,0.0
set dash_round_ends,on
set dash_width,3.0
set dash_radius,0.0
print("this is PSN_metapath.pml")



# =========================================== #
# PLEASE DO NOT EDIT ANYTHING BELOW THIS LINE #
# =========================================== #



cmd.load(mol_file_name, "molcart")
dss molcart
hide everything, molcart
color cartoon_color, molcart
show cartoon, molcart

sele notpol, molcart and not polymer
show sticks, notpol
cmd.load(mol_file_name, "psg")
hide everything, psg
# link: A:A:F146 A:A:F43
cmd.dist("link1", "psg and A/A/146/CA", "psg and A/A/43/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link1
# link: A:A:F43 A:A:H41
cmd.dist("link2", "psg and A/A/43/CA", "psg and A/A/41/CA", label = 0, width = link_size_value_from_50_to_60)
color color_value_from_50_to_60, link2
# link: A:A:H41 A:A:S54
cmd.dist("link3", "psg and A/A/41/CA", "psg and A/A/54/CA", label = 0, width = link_size_value_from_50_to_60)
color color_value_from_50_to_60, link3
# link: A:A:I71 A:A:S54
cmd.dist("link4", "psg and A/A/71/CA", "psg and A/A/54/CA", label = 0, width = link_size_value_from_50_to_60)
color color_value_from_50_to_60, link4
# link: A:A:I71 A:A:V39
cmd.dist("link5", "psg and A/A/71/CA", "psg and A/A/39/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link5
# link: A:A:F85 A:A:V39
cmd.dist("link6", "psg and A/A/85/CA", "psg and A/A/39/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link6
# link: A:A:F85 A:A:Y122
cmd.dist("link7", "psg and A/A/85/CA", "psg and A/A/122/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link7
# link: A:A:L37 A:A:Y122
cmd.dist("link8", "psg and A/A/37/CA", "psg and A/A/122/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link8
# link: A:A:F43 A:A:Y83
cmd.dist("link9", "psg and A/A/43/CA", "psg and A/A/83/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link9
# link: A:A:I126 A:A:Y83
cmd.dist("link10", "psg and A/A/126/CA", "psg and A/A/83/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link10
# link: A:A:F147 A:A:I126
cmd.dist("link11", "psg and A/A/147/CA", "psg and A/A/126/CA", label = 0, width = link_size_value_from_90_to_100)
color color_value_from_90_to_100, link11
# link: A:A:F147 A:A:V151
cmd.dist("link12", "psg and A/A/147/CA", "psg and A/A/151/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link12
# link: A:A:F253 A:A:V151
cmd.dist("link13", "psg and A/A/253/CA", "psg and A/A/151/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link13
# link: A:A:F253 A:A:L247
cmd.dist("link14", "psg and A/A/253/CA", "psg and A/A/247/CA", label = 0, width = link_size_value_from_90_to_100)
color color_value_from_90_to_100, link14
# link: A:A:F243 A:A:L247
cmd.dist("link15", "psg and A/A/243/CA", "psg and A/A/247/CA", label = 0, width = link_size_value_from_90_to_100)
color color_value_from_90_to_100, link15
# link: A:A:F243 A:A:Y148
cmd.dist("link16", "psg and A/A/243/CA", "psg and A/A/148/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link16
# link: A:A:F146 A:A:I126
cmd.dist("link17", "psg and A/A/146/CA", "psg and A/A/126/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link17
# link: A:A:F147 A:A:F244
cmd.dist("link18", "psg and A/A/147/CA", "psg and A/A/244/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link18
# link: A:A:F244 A:A:F253
cmd.dist("link19", "psg and A/A/244/CA", "psg and A/A/253/CA", label = 0, width = link_size_value_from_50_to_60)
color color_value_from_50_to_60, link19
# link: A:A:F85 A:A:L98
cmd.dist("link20", "psg and A/A/85/CA", "psg and A/A/98/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link20
# link: A:A:L87 A:A:Y122
cmd.dist("link21", "psg and A/A/87/CA", "psg and A/A/122/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link21
# link: A:A:L87 A:A:L98
cmd.dist("link22", "psg and A/A/87/CA", "psg and A/A/98/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link22
# link: A:A:L87 A:A:W120
cmd.dist("link23", "psg and A/A/87/CA", "psg and A/A/120/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link23
# link: A:A:R125 A:A:W97
cmd.dist("link24", "psg and A/A/125/CA", "psg and A/A/97/CA", label = 0, width = link_size_value_from_30_to_40)
color color_value_from_30_to_40, link24
# link: A:A:R127 A:A:W97
cmd.dist("link25", "psg and A/A/127/CA", "psg and A/A/97/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link25
# link: A:A:R127 A:A:Y128
cmd.dist("link26", "psg and A/A/127/CA", "psg and A/A/128/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link26
# link: A:A:G346 A:A:Y128
cmd.dist("link27", "psg and A/A/346/CA", "psg and A/A/128/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link27
# link: A:A:G346 A:A:R349
cmd.dist("link28", "psg and A/A/346/CA", "psg and A/A/349/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link28
# link: A:A:D345 A:A:R349
cmd.dist("link29", "psg and A/A/345/CA", "psg and A/A/349/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link29
# link: A:A:D342 A:A:W97
cmd.dist("link30", "psg and A/A/342/CA", "psg and A/A/97/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link30
# link: A:A:D342 A:A:Y128
cmd.dist("link31", "psg and A/A/342/CA", "psg and A/A/128/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link31
# link: A:A:F243 A:A:L171
cmd.dist("link32", "psg and A/A/243/CA", "psg and A/A/171/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link32
# link: A:A:F596 A:A:Y180
cmd.dist("link33", "psg and A/A/596/CA", "psg and A/A/180/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link33
# link: A:A:S179 A:A:Y180
cmd.dist("link34", "psg and A/A/179/CA", "psg and A/A/180/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link34
# link: A:A:E175 A:A:S179
cmd.dist("link35", "psg and A/A/175/CA", "psg and A/A/179/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link35
# link: A:A:E175 A:A:Y148
cmd.dist("link36", "psg and A/A/175/CA", "psg and A/A/148/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link36
# link: A:A:F596 A:A:N193
cmd.dist("link37", "psg and A/A/596/CA", "psg and A/A/193/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link37
# link: A:A:N193 A:A:Y661
cmd.dist("link38", "psg and A/A/193/CA", "psg and A/A/661/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link38
# link: A:A:P591 A:A:Y661
cmd.dist("link39", "psg and A/A/591/CA", "psg and A/A/661/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link39
# link: A:A:P591 A:A:W606
cmd.dist("link40", "psg and A/A/591/CA", "psg and A/A/606/CA", label = 0, width = link_size_value_from_80_to_90)
color color_value_from_80_to_90, link40
# link: A:A:L87 A:A:Y111
cmd.dist("link41", "psg and A/A/87/CA", "psg and A/A/111/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link41
# link: A:A:H96 A:A:Y111
cmd.dist("link42", "psg and A/A/96/CA", "psg and A/A/111/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link42
# link: A:A:H96 A:A:T335
cmd.dist("link43", "psg and A/A/96/CA", "psg and A/A/335/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link43
# link: A:A:W606 A:A:W659
cmd.dist("link44", "psg and A/A/606/CA", "psg and A/A/659/CA", label = 0, width = link_size_value_from_70_to_80)
color color_value_from_70_to_80, link44
# link: A:A:W613 A:A:W659
cmd.dist("link45", "psg and A/A/613/CA", "psg and A/A/659/CA", label = 0, width = link_size_value_from_30_to_40)
color color_value_from_30_to_40, link45
# link: A:A:L641 A:A:W613
cmd.dist("link46", "psg and A/A/641/CA", "psg and A/A/613/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link46
# link: A:A:L641 A:A:P622
cmd.dist("link47", "psg and A/A/641/CA", "psg and A/A/622/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link47
# link: A:A:P622 A:A:W588
cmd.dist("link48", "psg and A/A/622/CA", "psg and A/A/588/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link48
# link: A:A:R550 A:A:W588
cmd.dist("link49", "psg and A/A/550/CA", "psg and A/A/588/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link49
# link: A:A:N551 A:A:R550
cmd.dist("link50", "psg and A/A/551/CA", "psg and A/A/550/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link50
# link: A:A:D564 A:A:N551
cmd.dist("link51", "psg and A/A/564/CA", "psg and A/A/551/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link51
# link: A:A:D564 A:A:G566
cmd.dist("link52", "psg and A/A/564/CA", "psg and A/A/566/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link52
# link: A:A:E471 A:A:G566
cmd.dist("link53", "psg and A/A/471/CA", "psg and A/A/566/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link53
# link: A:A:E471 A:A:I497
cmd.dist("link54", "psg and A/A/471/CA", "psg and A/A/497/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link54
# link: A:A:I497 A:A:V489
cmd.dist("link55", "psg and A/A/497/CA", "psg and A/A/489/CA", label = 0, width = link_size_value_from_30_to_40)
color color_value_from_30_to_40, link55
# link: A:A:V489 A:A:Y415
cmd.dist("link56", "psg and A/A/489/CA", "psg and A/A/415/CA", label = 0, width = link_size_value_from_30_to_40)
color color_value_from_30_to_40, link56
# link: A:A:M655 A:A:W659
cmd.dist("link57", "psg and A/A/655/CA", "psg and A/A/659/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link57
# link: A:A:M612 A:A:M655
cmd.dist("link58", "psg and A/A/612/CA", "psg and A/A/655/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link58
# link: A:A:F608 A:A:M612
cmd.dist("link59", "psg and A/A/608/CA", "psg and A/A/612/CA", label = 0, width = link_size_value_from_40_to_50)
color color_value_from_40_to_50, link59
# link: A:A:F608 A:A:L534
cmd.dist("link60", "psg and A/A/608/CA", "psg and A/A/534/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link60
# link: A:A:I547 A:A:L534
cmd.dist("link61", "psg and A/A/547/CA", "psg and A/A/534/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link61
# link: A:A:H544 A:A:I547
cmd.dist("link62", "psg and A/A/544/CA", "psg and A/A/547/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link62
# link: A:A:D564 A:A:H544
cmd.dist("link63", "psg and A/A/564/CA", "psg and A/A/544/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link63
# link: A:A:I417 A:A:Y441
cmd.dist("link64", "psg and A/A/417/CA", "psg and A/A/441/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link64
# link: A:A:G488 A:A:I417
cmd.dist("link65", "psg and A/A/488/CA", "psg and A/A/417/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link65
# link: A:A:G488 A:A:Y415
cmd.dist("link66", "psg and A/A/488/CA", "psg and A/A/415/CA", label = 0, width = link_size_value_from_20_to_30)
color color_value_from_20_to_30, link66
# link: A:A:H482 A:A:Q529
cmd.dist("link67", "psg and A/A/482/CA", "psg and A/A/529/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link67
# link: A:A:Q529 A:A:V560
cmd.dist("link68", "psg and A/A/529/CA", "psg and A/A/560/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link68
# link: A:A:V552 A:A:V560
cmd.dist("link69", "psg and A/A/552/CA", "psg and A/A/560/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link69
# link: A:A:L530 A:A:V552
cmd.dist("link70", "psg and A/A/530/CA", "psg and A/A/552/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link70
# link: A:A:F608 A:A:L530
cmd.dist("link71", "psg and A/A/608/CA", "psg and A/A/530/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link71
# link: A:A:I417 A:A:I490
cmd.dist("link72", "psg and A/A/417/CA", "psg and A/A/490/CA", label = 0, width = link_size_value_from_10_to_20)
color color_value_from_10_to_20, link72
# link: A:A:I126 A:A:Q150
cmd.dist("link73", "psg and A/A/126/CA", "psg and A/A/150/CA", label = 0, width = link_size_value_from_30_to_40)
color color_value_from_30_to_40, link73
# link: A:A:Q150 A:A:R125
cmd.dist("link74", "psg and A/A/150/CA", "psg and A/A/125/CA", label = 0, width = link_size_value_from_30_to_40)
color color_value_from_30_to_40, link74
# node: A:A:F146
sele node1, psg and A/A/146/CA
color color_value_from_30_to_40, node1
alter node1, vdw = node_size_value_from_30_to_40
show sphere, node1

# node: A:A:F43
sele node2, psg and A/A/43/CA
color color_value_from_50_to_60, node2
alter node2, vdw = node_size_value_from_50_to_60
show sphere, node2

# node: A:A:H41
sele node3, psg and A/A/41/CA
color color_value_from_50_to_60, node3
alter node3, vdw = node_size_value_from_50_to_60
show sphere, node3

# node: A:A:S54
sele node4, psg and A/A/54/CA
color color_value_from_50_to_60, node4
alter node4, vdw = node_size_value_from_50_to_60
show sphere, node4

# node: A:A:I71
sele node5, psg and A/A/71/CA
color color_value_from_50_to_60, node5
alter node5, vdw = node_size_value_from_50_to_60
show sphere, node5

# node: A:A:V39
sele node6, psg and A/A/39/CA
color color_value_from_40_to_50, node6
alter node6, vdw = node_size_value_from_40_to_50
show sphere, node6

# node: A:A:F85
sele node7, psg and A/A/85/CA
color color_value_from_40_to_50, node7
alter node7, vdw = node_size_value_from_40_to_50
show sphere, node7

# node: A:A:Y122
sele node8, psg and A/A/122/CA
color color_value_from_20_to_30, node8
alter node8, vdw = node_size_value_from_20_to_30
show sphere, node8

# node: A:A:L37
sele node9, psg and A/A/37/CA
color color_value_from_0_to_10, node9
alter node9, vdw = node_size_value_from_0_to_10
show sphere, node9

# node: A:A:Y83
sele node10, psg and A/A/83/CA
color color_value_from_20_to_30, node10
alter node10, vdw = node_size_value_from_20_to_30
show sphere, node10

# node: A:A:I126
sele node11, psg and A/A/126/CA
color color_value_from_80_to_90, node11
alter node11, vdw = node_size_value_from_80_to_90
show sphere, node11

# node: A:A:F147
sele node12, psg and A/A/147/CA
color color_value_from_90_to_100, node12
alter node12, vdw = node_size_value_from_90_to_100
show sphere, node12

# node: A:A:V151
sele node13, psg and A/A/151/CA
color color_value_from_40_to_50, node13
alter node13, vdw = node_size_value_from_40_to_50
show sphere, node13

# node: A:A:F253
sele node14, psg and A/A/253/CA
color color_value_from_90_to_100, node14
alter node14, vdw = node_size_value_from_90_to_100
show sphere, node14

# node: A:A:L247
sele node15, psg and A/A/247/CA
color color_value_from_90_to_100, node15
alter node15, vdw = node_size_value_from_90_to_100
show sphere, node15

# node: A:A:F243
sele node16, psg and A/A/243/CA
color color_value_from_90_to_100, node16
alter node16, vdw = node_size_value_from_90_to_100
show sphere, node16

# node: A:A:Y148
sele node17, psg and A/A/148/CA
color color_value_from_80_to_90, node17
alter node17, vdw = node_size_value_from_80_to_90
show sphere, node17

# node: A:A:F244
sele node18, psg and A/A/244/CA
color color_value_from_50_to_60, node18
alter node18, vdw = node_size_value_from_50_to_60
show sphere, node18

# node: A:A:L98
sele node19, psg and A/A/98/CA
color color_value_from_10_to_20, node19
alter node19, vdw = node_size_value_from_10_to_20
show sphere, node19

# node: A:A:L87
sele node20, psg and A/A/87/CA
color color_value_from_30_to_40, node20
alter node20, vdw = node_size_value_from_30_to_40
show sphere, node20

# node: A:A:W120
sele node21, psg and A/A/120/CA
color color_value_from_10_to_20, node21
alter node21, vdw = node_size_value_from_10_to_20
show sphere, node21

# node: A:A:R125
sele node22, psg and A/A/125/CA
color color_value_from_30_to_40, node22
alter node22, vdw = node_size_value_from_30_to_40
show sphere, node22

# node: A:A:W97
sele node23, psg and A/A/97/CA
color color_value_from_30_to_40, node23
alter node23, vdw = node_size_value_from_30_to_40
show sphere, node23

# node: A:A:R127
sele node24, psg and A/A/127/CA
color color_value_from_20_to_30, node24
alter node24, vdw = node_size_value_from_20_to_30
show sphere, node24

# node: A:A:Y128
sele node25, psg and A/A/128/CA
color color_value_from_20_to_30, node25
alter node25, vdw = node_size_value_from_20_to_30
show sphere, node25

# node: A:A:G346
sele node26, psg and A/A/346/CA
color color_value_from_10_to_20, node26
alter node26, vdw = node_size_value_from_10_to_20
show sphere, node26

# node: A:A:R349
sele node27, psg and A/A/349/CA
color color_value_from_10_to_20, node27
alter node27, vdw = node_size_value_from_10_to_20
show sphere, node27

# node: A:A:D345
sele node28, psg and A/A/345/CA
color color_value_from_10_to_20, node28
alter node28, vdw = node_size_value_from_10_to_20
show sphere, node28

# node: A:A:D342
sele node29, psg and A/A/342/CA
color color_value_from_10_to_20, node29
alter node29, vdw = node_size_value_from_10_to_20
show sphere, node29

# node: A:A:L171
sele node30, psg and A/A/171/CA
color color_value_from_10_to_20, node30
alter node30, vdw = node_size_value_from_10_to_20
show sphere, node30

# node: A:A:F596
sele node31, psg and A/A/596/CA
color color_value_from_80_to_90, node31
alter node31, vdw = node_size_value_from_80_to_90
show sphere, node31

# node: A:A:Y180
sele node32, psg and A/A/180/CA
color color_value_from_80_to_90, node32
alter node32, vdw = node_size_value_from_80_to_90
show sphere, node32

# node: A:A:S179
sele node33, psg and A/A/179/CA
color color_value_from_80_to_90, node33
alter node33, vdw = node_size_value_from_80_to_90
show sphere, node33

# node: A:A:E175
sele node34, psg and A/A/175/CA
color color_value_from_80_to_90, node34
alter node34, vdw = node_size_value_from_80_to_90
show sphere, node34

# node: A:A:N193
sele node35, psg and A/A/193/CA
color color_value_from_80_to_90, node35
alter node35, vdw = node_size_value_from_80_to_90
show sphere, node35

# node: A:A:Y661
sele node36, psg and A/A/661/CA
color color_value_from_80_to_90, node36
alter node36, vdw = node_size_value_from_80_to_90
show sphere, node36

# node: A:A:P591
sele node37, psg and A/A/591/CA
color color_value_from_80_to_90, node37
alter node37, vdw = node_size_value_from_80_to_90
show sphere, node37

# node: A:A:W606
sele node38, psg and A/A/606/CA
color color_value_from_80_to_90, node38
alter node38, vdw = node_size_value_from_80_to_90
show sphere, node38

# node: A:A:Y111
sele node39, psg and A/A/111/CA
color color_value_from_10_to_20, node39
alter node39, vdw = node_size_value_from_10_to_20
show sphere, node39

# node: A:A:H96
sele node40, psg and A/A/96/CA
color color_value_from_10_to_20, node40
alter node40, vdw = node_size_value_from_10_to_20
show sphere, node40

# node: A:A:T335
sele node41, psg and A/A/335/CA
color color_value_from_10_to_20, node41
alter node41, vdw = node_size_value_from_10_to_20
show sphere, node41

# node: A:A:W659
sele node42, psg and A/A/659/CA
color color_value_from_70_to_80, node42
alter node42, vdw = node_size_value_from_70_to_80
show sphere, node42

# node: A:A:W613
sele node43, psg and A/A/613/CA
color color_value_from_30_to_40, node43
alter node43, vdw = node_size_value_from_30_to_40
show sphere, node43

# node: A:A:L641
sele node44, psg and A/A/641/CA
color color_value_from_20_to_30, node44
alter node44, vdw = node_size_value_from_20_to_30
show sphere, node44

# node: A:A:P622
sele node45, psg and A/A/622/CA
color color_value_from_20_to_30, node45
alter node45, vdw = node_size_value_from_20_to_30
show sphere, node45

# node: A:A:W588
sele node46, psg and A/A/588/CA
color color_value_from_20_to_30, node46
alter node46, vdw = node_size_value_from_20_to_30
show sphere, node46

# node: A:A:R550
sele node47, psg and A/A/550/CA
color color_value_from_20_to_30, node47
alter node47, vdw = node_size_value_from_20_to_30
show sphere, node47

# node: A:A:N551
sele node48, psg and A/A/551/CA
color color_value_from_20_to_30, node48
alter node48, vdw = node_size_value_from_20_to_30
show sphere, node48

# node: A:A:D564
sele node49, psg and A/A/564/CA
color color_value_from_40_to_50, node49
alter node49, vdw = node_size_value_from_40_to_50
show sphere, node49

# node: A:A:G566
sele node50, psg and A/A/566/CA
color color_value_from_40_to_50, node50
alter node50, vdw = node_size_value_from_40_to_50
show sphere, node50

# node: A:A:E471
sele node51, psg and A/A/471/CA
color color_value_from_40_to_50, node51
alter node51, vdw = node_size_value_from_40_to_50
show sphere, node51

# node: A:A:I497
sele node52, psg and A/A/497/CA
color color_value_from_40_to_50, node52
alter node52, vdw = node_size_value_from_40_to_50
show sphere, node52

# node: A:A:V489
sele node53, psg and A/A/489/CA
color color_value_from_30_to_40, node53
alter node53, vdw = node_size_value_from_30_to_40
show sphere, node53

# node: A:A:Y415
sele node54, psg and A/A/415/CA
color color_value_from_30_to_40, node54
alter node54, vdw = node_size_value_from_30_to_40
show sphere, node54

# node: A:A:M655
sele node55, psg and A/A/655/CA
color color_value_from_40_to_50, node55
alter node55, vdw = node_size_value_from_40_to_50
show sphere, node55

# node: A:A:M612
sele node56, psg and A/A/612/CA
color color_value_from_40_to_50, node56
alter node56, vdw = node_size_value_from_40_to_50
show sphere, node56

# node: A:A:F608
sele node57, psg and A/A/608/CA
color color_value_from_40_to_50, node57
alter node57, vdw = node_size_value_from_40_to_50
show sphere, node57

# node: A:A:L534
sele node58, psg and A/A/534/CA
color color_value_from_20_to_30, node58
alter node58, vdw = node_size_value_from_20_to_30
show sphere, node58

# node: A:A:I547
sele node59, psg and A/A/547/CA
color color_value_from_20_to_30, node59
alter node59, vdw = node_size_value_from_20_to_30
show sphere, node59

# node: A:A:H544
sele node60, psg and A/A/544/CA
color color_value_from_20_to_30, node60
alter node60, vdw = node_size_value_from_20_to_30
show sphere, node60

# node: A:A:I417
sele node61, psg and A/A/417/CA
color color_value_from_20_to_30, node61
alter node61, vdw = node_size_value_from_20_to_30
show sphere, node61

# node: A:A:Y441
sele node62, psg and A/A/441/CA
color color_value_from_10_to_20, node62
alter node62, vdw = node_size_value_from_10_to_20
show sphere, node62

# node: A:A:G488
sele node63, psg and A/A/488/CA
color color_value_from_20_to_30, node63
alter node63, vdw = node_size_value_from_20_to_30
show sphere, node63

# node: A:A:H482
sele node64, psg and A/A/482/CA
color color_value_from_10_to_20, node64
alter node64, vdw = node_size_value_from_10_to_20
show sphere, node64

# node: A:A:Q529
sele node65, psg and A/A/529/CA
color color_value_from_10_to_20, node65
alter node65, vdw = node_size_value_from_10_to_20
show sphere, node65

# node: A:A:V560
sele node66, psg and A/A/560/CA
color color_value_from_10_to_20, node66
alter node66, vdw = node_size_value_from_10_to_20
show sphere, node66

# node: A:A:V552
sele node67, psg and A/A/552/CA
color color_value_from_10_to_20, node67
alter node67, vdw = node_size_value_from_10_to_20
show sphere, node67

# node: A:A:L530
sele node68, psg and A/A/530/CA
color color_value_from_10_to_20, node68
alter node68, vdw = node_size_value_from_10_to_20
show sphere, node68

# node: A:A:I490
sele node69, psg and A/A/490/CA
color color_value_from_10_to_20, node69
alter node69, vdw = node_size_value_from_10_to_20
show sphere, node69

# node: A:A:Q150
sele node70, psg and A/A/150/CA
color color_value_from_30_to_40, node70
alter node70, vdw = node_size_value_from_30_to_40
show sphere, node70

